// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9i3IcN5Yo+CuYmomQ1F0sSrK7180IRV+alG2OJZGXpOy4Y2ptMBNVhWYWkA0gSZUd",
	"ith/2D/cL9nAwSORmchHkUXq4ZyJaIuVeB4cHJz3+WOS8FXOGWFKTvb+mMhkSVYY/rmP8xPBr2lKxFlO",
	"Ev1TSmQiaK4oZ5O9egNkvl4SiTBD+0zSy4yg/ULxFdY90EmG1ZyLFXq8v3/yBOW2L0o4m9NFIaDVbDKd",
	"5ILnRChKYB04p29F1pz+fEkQZYoIhjO0v3+C9k+O0NvTV3oEtc7JZG8ilaBsMfkwnaRU5hlev8Er0hzp",
	"h2KF2Y4gOMV6ybYtYnhF0JwLpJbErzY6OmG6Y2pGnuMiU5M9JQoyrU3085KoJdEDUglL9jCgEtlBggku",
	"Oc8IZjDDe7PR/Q5guDYhMNBjvQH/BScJkfJJdBNcLDCjv8Mp7EtJF2xFmNJT/Zcg88ne5D93S1zZtYiy",
	"u1+o5XG85wc4SdjfOUwWW7ReBuJzhAu1JEzRxOBKCG7CitVk75cJxvnkXWThgmdkswWfVnt80IOQfxdU",
	"6DP8pbrqqUPAVgg1VlAukl/+iyQAif1LybNCkROslk1InJJcEKnXqe8Otm3RnGYE5Vgtm7cij46jIep7",
	"6yZIcYTNOJwBIsu1VGQ1Q2+4IkgtsUKYrRF5T6WibGGa3tAsQ5cE8WsibgRVisC9JO/xKs/0vnavsdjN",
	"+GIX5/ks44smPn2IwSDP+xFBrxHneWYxIUQAOE2pj+TfBU4zokGfcKYwZUQ0UWM6eb+ju+5cY6HvstRj",
	"2DUc+KHsD//bj+hb+IHN0t2K9AeLZzjLjueTvV+6Me47mhHX6cO0u+0pybCi1wZNdOMKXuofm8hVW99L",
	"dv0TFgZJKihDyg84Talui7OTSpMm3ayc00t2TQUHJEfXWFAgl1dkvXONs0IjHBVyiijT6yIpSgs9DBIF",
	"U3RFZkgf8xVZI8xSZHoQnCzRqpBKY9slUTeEMPQMGjz/21coWWKBE0WEDCiW23YLhjkwnHChmpimf0Ur",
	"nOd6YZRp8r7CCl1Mllwq/XHPI5T+62KCHpPZYjZFF5Nvnn7zdO+bpxeTJ9W7YH/XNxQrTWcne5P/++Ii",
	"/eue/p//ipHacJm1J3YYSkWOWyNL/eH0161nLGj2YTph0efxvHojzbvoDu3Z//f//L/Vo0IZZ4spkgoL",
	"hW6oWiKMMqIhg7hArFhdEjGFI7agRoyjmyVVROY4IbNBtOSPCWdkAKCOVnhB2sDddxmPWEZZe+93H951",
	"o+ApkbwQCXlFV9SwV3Wqb76jDBp4XqNG/qqnmuRFc6SDk7dmEI3TCRdElnj77GKi//N09n/9rYG7+scm",
	"4j6+uJjp/z75ZxR7V2TFxbq5iNfwu10HHHzBqCoX8vxvf1+ZtTxfXEyeoELqS3jC0xX2F/Hx5YvLtSJy",
	"iq5eXNFLav9YvVgR/8fixcJ9qW1Hz9Dczi+XV6vFu/8a/EbVj6/r5BLOpBKYsqHHl3lcGHi/a0jUt+gz",
	"hVUh48+s+QbcFtKwz6r32jIIKbmm5hq6d/dEkBzbJ/VMX2vzz9OCMfOvl0JwMZlO3rIrxm/YZDrR72tG",
	"FEmHP8vVHYRzNj4Gi2h8K1fV+OSW2fhQrrvxKdhIFdA/8aww1LIk2VVwH5I5ZVoaAoqZomvogQpJUnS5",
	"BkavC1PixPgto/8uiKHBllsKx9XXjrIYGjZxP2QtYLJ3d6SzBiQbkdjXvGDqFv1gvtbO7z5ED6v+1lbh",
	"bcAYueyvqFRwaYK7YhtrwFJFVptcaIs45T3GQuB178U23QxSdl/treDZmwaCRYVGQeZEEJaQGI20n7QM",
	"YghLnvE1SdHxwdGOhlFGMVOI6qPUrIG+03OcKHSJkyv9NHTOHUPgcD09b7M8K1YrLNYD6WWWhUCU7bTy",
	"B4IztVxPppNDshA4JWmEPm5ME6urLedobRJM3tomQg6rDfxyNegKtTwARU3z5uCc/kSEBKA1lEQnR/Yb",
	"Si09hGM1v5EUmRtiUI1KJJwkbN+kucZfc4IzdEaE7ojkkhcZ8I/XRCgkSMIXjP7uR5MO5TKsiFSlmgik",
	"DsN8rvAaCaLHRQULRoAmcoZec0EQZXO+h5ZK5XJvd3dB1ezqGzmjXF/xleZu1ruaiRX0slBcyN2UXJNs",
	"V9LFDhaJZmkTVQiyi3O6A4tlAOTZKv1P4ZiLuLrKaJEcweq+nrZxlwqlU9kjX4bqq5i+qtIaYUGcsgp4",
	"nuq8cf2VW0wXedV37BrTDKTKls1sQHELtfTwixHbkHoEGBylG4VaHq4ZXtHkuFVLVsP7vi4Iwz+lptMC",
	"ELYK5Uus6TdnAIlAWZphupIRsUD/ftKqFPrvs+M3XiGkkQbaG/2PFcPMxQwXgWiqj2BOiXBc/C8Xk4Xg",
	"RS6tUHExeadJ9y8Xk6SQilv+novFxeTdk8pZNVCweiBVlNTofSLInL6v6FQnk2lkbzk09Ox3ZQfAJ3kJ",
	"hIvFjpWBOm+Env6smA+bXkLDIdPvAFzi06texVhlYOzxKHx8UoNwES1pDd+V0WyWSNOD9acNFWsrtleb",
	"IvJeCZwoiQTPiERzwVdRjLbSIC4x9e44rqfcBXS16N5E4nfwF6zN/0FwtvrVaMoNOrvPGyJ0/5HqgR/s",
	"KDehXC0ky73gS35jyRacJzzc1UPVb4TZGEkbtE3vM6V6zhVlWHF436xSDtZj995B2bup8XSSE/FW6oez",
	"43EwTVqHkJoF6VzEGbTotH5o7LVWJ3MqmtIMkqgGTNA/QDeYhozQDaUPbcjW3S2Kc51dUCKI5uUQRpLk",
	"WGBVo7Rg5sLJEvCySTqGPC66pybRO0NeGWgsc5LQOU26iL4f9b4fnsEruvdnyF2+YbSrFYVamd/waykw",
	"GNNZnG2s2piRLPKcgwYJXXK1RMdHhwcgFBzroZ9HbdCjhLNVCeeKsojA8SNlKaJwy6GlNRN5kDmtwOnL",
	"s3PkJjBgNRAM0KEEpgYEZXNneLdvlhZi0pxTpixDTDWdkcUl6OI1mhKpNJxn6AAzxsHcUeQpViSdoSOG",
	"DvCKZAdYknsHpYae3NEgiwNzRRROscJ9MtExwOg1UVj3klYNNlSKMrq1dsnJHmqwHDtH3w3XEmD3LQcZ",
	"EfAic9JiyG7I8cbe/431jG+L+N44kC2I6SOd+Ch0Qp+poRKb3XZz4n3X3XuTdYgAGOetGFPzS5tOrr6R",
	"bY1//EbWGnONqM9bKSQwAPUuNG2VAzTrULNc1Pn+ijvRYP4/MnBPh+bSexn8Gij72tehqdn/VscppzUe",
	"ojuoKQ1COdPoDeryZKf0uT35srb24UJh3cNsa8JgY+DBQmC9Z9s17RQ6o6fX1cOrOXGW9egMwFXN2qUN",
	"nCvCRr9QFxdcQlNpRXi5WRKNVX5dzuvN4dn9CUgWi4bqdhr77D66IRcu1rI8Kgd+SZRTUwH70nuGzTOC",
	"vnGAOVYOtGBg9YI5YBGV2R5Q7bbhyZjdxY7jW6ySiJ4SfgbOhSGSEQA7ZegSfpaal2DGnhjxGolvaoXf",
	"01Wxso5ViAuUE5FoZnUBmzUmSgCtYUqQ9Q+AOfVUw0jQiR8ViM6KMj3tZO+Z37zmaBeai9OUX5KMJJb0",
	"drIa+JJkZ66x7liA5vV8KYhc8iztGyBc14e2gzizkG05EPe5Ig449AQ4GQBeEkTek6RQJNVQbD8v2Trf",
	"fnVcMyP1atFBPLPBLc3PUXZkOjxr3gOpBFZkse4b7ZRnGS/UmWteR3U/TgzND/Se5zTBipzRBaNscWoY",
	"4oiPWlvTigrHMdTGsojsi5+UfUu2/GB/FPtGRc2oqIEerbfLCSXSew7dbhjTfVvqn9Z54rqgzuZVxVBr",
	"05FYfHQdUefZDHr62t+bUXf0peqOuklb02lJ4DwHEzQvWIqwMYwZ+2GKDs5Op2jFU5IZ75qr4pIIRhSR",
	"iHIAJs7pLOA35Oz62axzCU3CQt7n1JiazkjCWRr1IIf+JkrG04xrnNGUqrU36gUL0dMYL3nDa3/1fNJk",
	"vSFSUOCuGJ/hklQt+EcPjLAyyEWkk6k1eK0jkYUxMGcazjnPiwx+ulzDr/snR0jCjdGwh/YgJesbuVoV",
	"Cl9mJBLqYxApylWegyQjyd+/3iEs4SlJ0cnL1+W/fzw4+89nT/VyZui14+SXBOmXaeZ5TUoy4OhxiA9d",
	"DKuhCpUjuVwrErs4wMKKuH7iiKUGyYy/iscJ08cQfCBV/y5wRueUpCAoRy9oQSPE7u3R4QOcU7AIiRcx",
	"ef8t/I6sedra8eFNuCJrZHoF+7ciKpWyqHL/m6kC9Jb73ZsfADA1UuiwuYIcm5G+Fj/wEqFwngt+jbPd",
	"lDCKs905plkhjGat8JcXdhnEYskWuCM6L+NEY+6HZdOWSG0zZFOem5aAQ1zL4B7mg26XJq9GfI5wjf6b",
	"cd42quPgps3Qj4zfMJQEDQVB+wA6kk7RIWFU/1dD6DtMbXj2ME7FjdnrfBpsIYoDfqD2DZbHlxKFaWaC",
	"kTgjCOsrp9xxJ4UQwIEocKCxvKtG6tOApNV0T1iqc4GZhJnOaZueVbdDiq6ImckvTfm+JDV8kV6XRUPF",
	"EWZcLY3q0J+2ZoB29FhxTkRqetESx498HL9th6i5E5qvc9DBl7xQdsV+eXHvnEu47un3hBHzTsd3P3Os",
	"zGzhWxqiUoXGDZZA+Yx7b5GbacN3/e9fR991QbCMCiro8aWgZP4EmRYl6+DmfCQH7XSggOhGdQJhqXAd",
	"1M0YweLaVLuCaQzlPADK8++8LP2BMhUYTQEp+RydCy1ofYczSabIBkCECmL9fTKdQIONIzpqq7Nj1X51",
	"Q9d+DoMxqtBs4qPVc5dYR0NJItiNo3ST6eT85PVPRACPYWJC3AdDA2HPmgA2m4K+ll5mpP6HoyknWEho",
	"erZmCfzjJ83n6hZG93jETgRfCCL14b/V4o8NNsxJ4pq+LjJF84wc3zAiJKzrmibkkGjJh0otV+hOww7i",
	"JRM8y1aEKfueBvttfKtut/VJDoZobeNh2drCA7m1RXU5pyTnkiou1lHQa4i3fmicT/jRn9V3GSHKnQL8",
	"ETs1cxrB2ZkfwhM0vww9R4Pmc7qouw0MM1d8T1Wke6+B23P/ZyQRRN0iXPwWs/6gVB7rBjDIC3cqrznT",
	"B93MFFB9r1emWX+mjVK3wZHt1M+6hqNH40W7s1s0d2J2KTh7+T7XuBRndARniPgGLlpcP3V67LTIQGtD",
	"V0TOLpjepG1BJfrtL8j+/297aAe9pkxLr3vot7/8hlZWIny687d/zNAO+oEXovHp+Vf60yFea6C95kwt",
	"qy2e7Xz1TLeIfnr2POj8MyFX9dH/PrtgZ8YflaRIHyRWXC9iRzfc80Kr5r6Npso68uphKENLvWQ/Hrkm",
	"Yg2/PdHz/rbz2x46xWxR9nq6881vALhnz9H+a33236D916b19Lc9BLo61/jZ9Nlz21oq4IKfPVdLtAIY",
	"mj67v+2hM0Xyclm7ro9ZTL3HmbHwV/fyTQkS/S5/E3S5YC9NgL+GHHq688302d93nn9ljzTKyhxALJIh",
	"LEdszrvUIXVuCrRFRuWbIhPUhJzvhll0S8ReVdwNBqHMICMIisB4VkNHG0yMWXhzceb3qrksX64lTXAW",
	"jDcquUeL2GgR2y0ZkOHSje1zC1vXu9Z73Egp0QygZu1p6UpxNvRj6s7tALJSum5xh7J+InPkMx1JdLOk",
	"yRJ0H9ATDUohoaeBLD8ROvrGz+LaICdJt+VJaYq8w84snvzkw7Q9oUMpA9omPleC8Wiqrut2+R3q4nGL",
	"7senLdDnFQDUb34QXlXD9mOvmjQNHP4sIYNALalFJKtBFU2pfUo70TR87Yy6xVE+UEKESTS2opDozunQ",
	"dGbpgarhw9sAeRDoz0otgoGXjTGKuMARlhJB0tZn+NQ2cA9v67h9WuXqPJ2blDxr5TDs55DRsMoS+Dnh",
	"jJHE6hX8YcecoIBZPzqMEyL7GR0dhiqr2gxxxDA9XwdPRw3fPa/nZ3GE2pE2SERqzA8vKtnrEszgtZRG",
	"WwzOWTijvxu1ps9SSMSKMpxN/ZqNe5juNkVEJW3HhdNjlq1detAKatZ2NQ0A2H6UodwcS8lld234TuxQ",
	"Kq1K214f3jhDhcWCqGHPZriUc+gXV/aZIYdtKRinSca9MclcFqlnaGxtRdSSp9UrFarA3jICCh9QcCWK",
	"i/UpkZX1dSmSulYcjNzVrDqrh8KRfgcFVeuDJUmu2ghSe9v67a2SLOp6oER3QTkR+kYYm/gt34Cd6BtQ",
	"Sjz1Oc2K7kD62zd/O9rfOlKPFnkDYJZY5zKOvWXSSf+hjtWr+DbBw9gGypm62oRraG/nV9fepFx3E6yt",
	"OnnLnLShaOPu5jUJHmaBXCVqfXukAQemTVmcEr2BvSkX3cPc6NYeVs33ka40J7jK3d5rg19Dz5JHHWY4",
	"u9Wtshn3zBE51lrlq7vA+dYXs7mYwVez9QEIlOkev+PX81ZXsXYtWrbUdrN67nDz+pbX7hWW6owQ1vZo",
	"uO/1hwJQTeoPKsRC3Hr/staJmmZhy38YKyhhzq1CS4a05k/Tgco1/PELaMegV3ROknWSkR84v3KI4zDg",
	"WzLnIrRd7M8VEcHfpsEpueQ8bFH+sAlmVJbSmDrSpr6a1mHCBbaNE6y5CZxbiT2Z670FgbGuHi0H3xa3",
	"UNvr7RiF2CBthCjMax6DWJMjMAZISw2qVrHqLxuSpNqq60Sl9rmyisj32NJ6mlXJU9TRu/xW9eo2v49x",
	"/h/fhzs4iUGaMWvMGN2zPzX37OnEKgWHnaDjurbn1x3zBzgkCmoHHBpHraaq3KgU+43bph1oliqh4Cgv",
	"RM6lQWBHe7tWEi05ArZKyhbgDtFxWeb6u4ttXWJljJw1RnSoP2sN7gEkGgsaCu5TInl23QFuFwsNzeMQ",
	"N3v0wflYIq4bo8esyDJE54hx8wtknNI/6mffacAihtQHOmC39+gB54JcU17I15sctD1j1zdbW5t2essD",
	"B3sAz4p2T68f+I1TnM4zmihgrIXdWAgAY3SH3Uymkzfc/Qv2dUhaUrV3olxtbe0odyzjgRrh16B4FKhZ",
	"QTuGjs+8arhVH7WKuoKeVwYxKaaNAU201IiqbdWM27mp2zDLx2eDt/BT1RjgthF/s/WXQ7poDZFI4Vt9",
	"LON+geQSP//b3/fw09ls9mQoaKqTdgAKLtuS5gdLzBYfh7LX1xC98ozcdFA5Rm4sXTP0zlM3QVb8mqTD",
	"iJsjDR0TuSbx2RhnZMhU7Re3/aS8999GiO2ZyT41nS1c0s9pVNfhVE4plVd36V9WLbndCHWn/byY+EHt",
	"6oaCthvHZcU3zwC7itRl/vefsbDC14GgiiY4u3W2+dhCw2T2za/l5LGvwYJin90iY99CV2f/vViRILVA",
	"3JtrDm7bE8zW1jOyqiUKM028qxfXghiw4PO7aTxiT4t3ApbjU2v4VN0wBXKpL7Sot8uFjS5zv87QvkIZ",
	"wZoaM1I2dgWVbCqVtFLZ5o/a6vcmpCzF9SIXPC3AXDpVlIgXcwHVxtIg7ZC9g9VNxvwE3HLMLpXQTEWY",
	"DSNIJ2KhYFR41O5TztBb6WLsbAHFFdb8ISqda2sgCYoV+SgKjZcvzGTPplb3ky+xJP/x4oSwlLLWFKY1",
	"SG13jzD4sD1WkSHY4xVZPzM252fTK7J+/h/mj+fxDX3oIipwKWTOmSS9t6JRwQi6GVEYtmkCZLx0HyCf",
	"gUJqBcHJ3lcfmj4O1Rbt/kAeuJpVviGCIJvxZV5k2doCPI05BDXcHSpTthPfLu6zXri0w42ydDMZViLm",
	"FrkQW+uUNQSDxJfiiC/EfL/FGqLu67HpZX9iJ5woel16dVh3hk1VR85ZJRqgXNVBbuymABFeA9dhxRgr",
	"lbUUBtvXS6s84NZhvpqBeDgMai7zMSiYip5pi5eN+egsLLLm7F8LHdBS4Ympnia7chcZNYats1bdTIPa",
	"2oRudh1QEk4T96kpEccF/JcXyuazniKT+GdJsmxHqnVG0CLjl24yWD/MjheYMqlcTGO2RhnHKTFTwJpW",
	"+P0rwhZqOdl7/re/V+rC/fJ05x945/f9nf/Zu7jY+XV2Af/3y8XFu/+4uNi5uPjLxcU/3/318f8a1u7J",
	"Px9fXMx+MQ1jn/+rPZVcV/kno2o84RlNBnKub4MePl9vG13s9ClpepHEDTUyqDxliSeyfVcYzOA0M+6e",
	"iSpwVoae3pXWWok6JLkhs7wBhWl66EZuGW76GW48es1Pc3j4sj8Fk8UQPGmdz6aGZDS2F8dUTrcMWQ5f",
	"nEEku3SiBK8Ka6++le+Bc5fYjo0ZPX5zfP5yz9gBfGAHlYhxhQRRhWCVcP8nA43SWqha8J1/Sc526IJx",
	"YUVzvXhnEruViXLDN8r3qbxSm8q8G5sHGphtCL6LvhkwQNm+601zt7/ynmx8781k6VtGVfuNt4aeTQhv",
	"2uLhElzzCmSqZGUSpzLhUYZ3yd9JwI9yveXJhajXwR/f2nk8uG1LLNIbyNLLXBSblifMXlHF4rh9p3K7",
	"BpdTYBtu5RHQ3M5XYKM6g3EPpWMILI2XFAx9Pk64lqfS4/m84sK0f4Opgvhh61dtgsvBYHCCC7mhG0Fl",
	"Q8HSGt+C1Ua+VhVAlU9NP5bK58o2I9/rjg2VjzFgRJrV4VMeZ4WsDQsqPM6dM7q5DUEOJfI+57J8b/CC",
	"MDW7YC9xsoTMOAkXAiT11OTKKMUIcy2sb0GCc3xJM6rWswvWH55oNlG5VQnPMlO13dvGW9kzvchWpwv9",
	"Hu8voEK8aRK9hKG5u2WMoIXmf0x8rIVTI3iyHFmjTizk4FvOFTo63GQoE/055AlrBJzqN9sRQQPt+C6P",
	"PaU8c5Ry4PLqVvgQoB4KzVVMq8fXTrcakkSP/30OLcEss8IML0ptkvWYkFNEWZIVqf5ysyTM/e5cai4J",
	"SvkNs1Kcfkds1p6Iy69td2aCv3sZK7MZ39o/7rft/6EHbOmtjINmTVt1owufR5v+eYvPY2Wzt3sem0Ns",
	"4EhXAsx70eXn/BBDqqjjQh3P7b8D78nbWEUqiwymiHwNZ412rrlxVr82DB+hqNnDljnFqgtwAsOhF2jg",
	"ws2J8WYo8+yD/b9TAi8xue2xG5C8yFcy+6PxFu2jS0Hwlb7RnTu5XKOLcF0Xk6ZLaIlcss7TfgKLt2vq",
	"XrjiCmctxkH9KYjfjc00MJmUpX6fEnSs9NIFnXogGYBqGkHW+vnXNhylRlRe9SZa2Ti3yfQTS84SfcCT",
	"soKiHQDebiqvTGLGJnnIW2uwplSAuWvtC7E6/bf11wjG7N5LHq9l+s6clShg1m+L1IYn1lSYtRbVxP7k",
	"mmS24jS/Ialelm1tyKQw+Y0QBTzNbZKjJhigiOy363YlhTEBXpE1MO82LAxBNw1i79tUzn8Jy63oMQKt",
	"9eNf9nf+B+/8/nTnH+9+2fH//nV39u4vT/4ZfBygbwb1+FvmK263VJcwZR4CquPOKKjV7S51WgDmWPCB",
	"Br6jSgR83e+ZvlbcYo4K1pzXn+NG80d5uCLM8eeqbz6V0fqbbnE+ga9bh09wYIKkFUeaXmREkRmCS+Lr",
	"UHrG1yVGBf9JjCCnF7228UtE3x479uUaYaPqLBhVM1SmDvI/QhLLPfSbNFl4pElBPEW/rcwPJrGO/mFp",
	"foAUQoDeAar9c++XZzv/eHdxkf7lyT8vLtJf5GoZx6uXLOGaqR8SpUtsW0PnIMgaCANWuOZ+XykommGq",
	"xVqT6Hdwjjcz1Ynt7P7+1g7yIUz1duC127VMzr7FjtUf93HG5ZhntkOdskXGjL1IjTx0Tdg2mnSU0rDp",
	"YDU2mgV0GmDGoIoxZ9CfMGdQ40Jtlj6o2X27VTNa0lbGBIbWpmWq4LjGwBOKwIKISpLVnioCu/yXHUmp",
	"b5ZELYkIczCjJZbokhCG3ADBmV9ynhHMvFtXp7DSo/TcdxnHzUigTs3zbO1IS2tCtsbh2X1udEKBrDVI",
	"nGg/6iYf3zNp34kHFvy7nv1+i/s58CZY2TxT4enfYFk5+GGR7K7Ht+v+mn+27QDxKRh1Gm4pIoVMNzyC",
	"W7hRRADvD2gWxbV4SGW0WTW6stFkZAk+epxl9EwGGbebjOMYfPml1saJMyz9NAD8XqlxePUNDfVptH0k",
	"XSgVuBZFIjtkSyxLrBJLWFRCmsTW4bsSecSrvmrD0zdOJ6BNP+1Lv3YOz1FnCjZAWZthavYvyRl6zK1R",
	"t8MJfavciisl4NyYoFptwMBQ6R2floQhfYeCB4TKGHvVwuHo8xyGbC1WrpaGm72Cgx6lkv29FTMVOOL1",
	"FTAJcblZxWS2cW2SZiUOcgeav7VqI031Rcfp2iZdDOaS31gFmCbBcOvB7xej7zK6WCp0oEkyz0JkDbLB",
	"1M67UEtNlhOvpNtIE7NfKCibGihgCrrjXqH4sb89feVO5+1ReQvBiI4KaRyqc+Fesf99ijSKAPeRUXZl",
	"8mDDfO7t7HA4uK2KqU3TVINXOUErDAahBMCxHy10s2pdIfvGV5dVQRpT9fUWqGGG3gmu5E48N+QBNAyq",
	"KxxihctlhtcctJJA+rFbuh4fzWkGMT/o/NVZ/OKbxVyRdecifiTrjSa/Iuu+ueuXvQUqzSUOOvjhJGEA",
	"ZXBJPvW14Lc89GBfGqm4oKoV5GXbfde0Hfohl+JHRpWygG0XOBbYazhh/QoD8UhTQaT3/ujdOHrsmNol",
	"l0rLtns5F2pAqHYHgPxioyd/Ha0cDz9XdczWj4BcG+d0rBBPwBPdF3EzTm8RYh6Pz6uL71CdDcwYBhaG",
	"BAu6WAC/BnKEntyYVoy84ir554LM6XtjNSEUNE96uD30GMwe4EADFeafBDPYr7hQfAWl31zoTJzTGwXj",
	"bQvGaZkhoPMV1CO6bAIQZHANaS+M1neYbviUzImAQu2jSLxtkbilSNu+uXdlstiaAFrPVavhmNuCalu0",
	"BrSXU5NLLtQUrXCypIyU67THD/Snmq2kVnjNkKPAfOlcQw5Mecmg0NKBLSDp0z+6D2+9L3/1l0ZDl7ul",
	"9ks4ZjPsseXnWo+Dk7eNIP6Dk7f1sP+Dk7dv9NNeNnoNWREafc3P9e7m19oIh1ReNfrrH+u99W+1vkG8",
	"VdXHPPjQcE0PvtWTHhxSaVmVMEFnxEm95jNe/9nnGwo+1EY9gLh91fAwtL83fQt9h6hXoT/PjcqdOdm4",
	"hg0t2bG680p11AHTvxyxa/vbkX2kzrG88hOHP54QscIM4jyDO9BS+8z9fMRw9YOl9mnZpLxozTpn5fLC",
	"smflLQ5/PVNYNH/1S60MYJ1B6r9/i1WyPKQyN0mjal8t1Ejm4N7oGo4bVnI70BdcBSc2qDhcA3blp2i9",
	"OP0jZYsGgarUkqv/6Fsb7/RTIhUXLfl5TM9BXMGZaRrUpmx3tAsYyGNTAtLQkymytCak5J7UODr0rt+m",
	"1K3ZrTItkSqXU18d02xqahnnVrY9SLAU4d53rKdR4mqhTvXDVsA7n5aZTCw/v85B6qrkWTKB4nluA+47",
	"qUOnnrY7818PYdlg5HqSu7bMVD2hlS15rDovYsuI7T06Rg0ow9Bhyy7xcTdaaM8aa/RpwIDVHvFRLYEY",
	"MJppGR/FEecBw9im5TiRl6m1/mO9ZXyU5lM2YMBGp3Lsrmet1Vm5tUs4buUN6caUaOPmWL3rqjQLpDsX",
	"qW3q6IcJzT5MB5YEbR18UGR1y/Uf1rub1N1mjDpR6y9O2oacm/RsxcKhlT+j6NHfuRdb+4bouOKbdN1s",
	"053Uc5POLcR84yHutIg4uf7wbqNMg8CDtPipuE8135Rr0JyMDikf3SHFH8QwLxRQIY+eJ1+s50kgaEUF",
	"LL8KozKDawY557RE2VSW1Sw7rnO/gWDDeXoMJn7e2J6/o5lTubTtGT4aB4Y5jdXESLr6Q6ADUuS9Qo/f",
	"nn+38w0YJkzYQ2mbKieBGDo7Tcz9QLdzcQ/9VuUgjCMaHaO33150T3/1ZfZagqVaMojTjDySJi5qGoTC",
	"WJMNRMS45M2sWBFBE3R0OEOHJkIHCO/FRHCuLibxW8JT0jl1ToTVgSLddob+Dy+AeJjFmFD8lb7qc7yi",
	"GcUC8UThzPkyZARDVMvvRHCX6PHp37/+Go4PGzerhK5sB1OKL9bn6+dPn2jqpQqa7kqiFvo/iiZXa3Rp",
	"A3uQr/UzQ0dzyFrkITY1kfjVzcAV0PuUKA0AppcXL7tayNZU7wZakJn4Hg6qDeeOnf4/LNqTeDWczcAc",
	"ZMAZFiBUGTrQ6oU/n/qxKz87MeadXeFmoaIhGenlwMI719d4/xJSspMTDI4ufzQDKj1VaAmtBIYvcrdt",
	"MHlo+CVhrtSRPxtjiMYYolJm2ixuyHTZbqwQjBmXtPynqqRlalyMN/mjS1rlQQyStAzNHiWtL1XS6lfj",
	"NMKWL6G8S5SHg0/AhlYTxZRB8w9TkqfDahKz/s2tpjwqDfrsAKZVPcsIbHlgZhSbjPyEiERTqbbaMraZ",
	"5rVtOyeO3WKyeZH1baxseZfNKbLKNc3sDIUIZevzagfn/0ylRSNN0a1rM7jw8yj+KLoi6XGh+jYJ7WCg",
	"u+zx1gl0hs/SVRapDuOpvYwx1Jr6HDYBJnhcDwA3iCw0FcRfBF0I7J4xwvBRcPo2CNB3hv1U/d7h3U2C",
	"twjpCm5piLsEKZAO5I4A7wN03JDx8NCuWcyjr55ubkyefcA2IPUBKjYWTGM1gUS8xKX3jMJ3e6fbMTXU",
	"U2Ep2fSASyhsfthVi93DH7K18D/ofbJc0P3fpJol9eGh6xw7YuAVronAiiwiiQLsGFoMghbe3an09oLU",
	"xt/e++tTfXLu/N7Udz7gGKNhnM02m0VwNjiImiXEhEB+28eTWIatrPNhyIopT10DWGd2r1IzE99qR1A0",
	"bKU3ENpudVjBjtNKYwgeKmtWdUqYlQJXARK2XDL7tVZKs5k3spap8N4UZEFVpka62Lg2q5740e23FbE7",
	"MfrWqDy4sAm0niICFhKcZWtES2kjuBpLfE3AggMxaOaNhMRyDC9IJQKMMoTRzbLNorhZmLE/8btXBUkb",
	"WWo3qSTtSdUgFVeVWm0Y1/w9YUTQ5JTk3Btruqql5ZFg/T4vJTO0c0orRIsY+jjn4Fa9htqhijyBpN/G",
	"rWlYcVo9tG0T3StVkTJejdd5QdWp3k48H4J1uTKxmd9TVS1ghUzw4CapQV1CUFevmC4cBSq9uqKcaQmd",
	"/ue1HMqrLuPcLtDxU3JNu3JCmK960YWrlNe73kaVOr/4xqzTtiSn0wkbxPPXqrz1r4YZJtqefGziHzi/",
	"2k+csbW0Z9Yyks87yxWZUue2oOWKqEhGzEuCyHuSFMokpBhEifTaOqmRoivC2/RMn3S6TvRIPqpm63y0",
	"elTN1olZih4tH909Y+eHWGbgYS60JXacFmzy4R3YjKs/RlJoXv+ExV1yobwsa52iaywohONdkfWOsVzk",
	"mAooLvAvI2a6NLAF0zCOZtkWBWt1WlppQFcxNKxcgNkaYbEoVsA5FBIkXIVZikVqqtYhuWYKv9fIQ32p",
	"U3PuEq2sF6+bSaKc5iAbLyA13lRjFIXrvTblMd0iUKFFZ4TRJZZLtJMYP6D3cdXcDRdXh7TFjUN/NCme",
	"XbJms11Ix2oyIBeMOTuQXegAUlewVpJSXtu9TXDNdzvBanmc9zpAVPq8fK8ZPFPmsXddQeOmkZMh4j8H",
	"xI1o/IOSChwpURB9dJ4NidM8mwOapNFTi225cZ94ixeVj5J9LJ8gPT+4/GAFHmQk4zfGOQheYb0FiRWV",
	"1rUJfvVLH255rDjnRAhyOzeArauKZwuMvxwCFYBHSw9q4JQT43p/RzDH8oxPNVSjOKJUXuYG3qC+7kGF",
	"W9KL/OH8/MQU39CUIMLG41kiIm+XyVeMnPef4Fyhg/0o/uRYyhsu0jYGzHxFNr2B0fZH1uXtH368WDje",
	"Fc2N8fcnInwW+UjqiyuaW0bXMo3oOugQT/apMjkIGOevzkxKFudzOGjpevQrsh4++hVZDx+cX7WVKYRP",
	"24F+IYlo5xHd1965BjjglTegW5pYKpUPFCeYWckwgUJThZMoGdG/OhHCyKGPpCEits6W4kHCUec1Wy/x",
	"CEuRRONlyd/dCKoUYXcWR0RTHHHSBLb1w9csQR2CiimKG9u88B7Ab09fGVKZ8JUm+XNlU+xeYglfZ+hI",
	"oQQzy8YQ9O+CQIkGgVdEgctNkSwRlnvoYrKrKeKu4rvOdeOf0PoFtG7z22wVefzxPbyU4zCyja7fUhew",
	"rDwJndxI2TIIRd6KDgGwFs6dowRnmX43k4wzI6VGMQli2U2VlBac0uMZfDOsIGeZKejlumr21/g9WDm+",
	"PGooiS8kWkEuI43gDjMNAwxyErxddtWO37xcuwO2HlNIn4VmqmElRFo+GnL6LEmWG1qmTLIfuyNfmlKp",
	"3LscbaRHmYbnGsOYoxVekLYK7YNdf4MBfuJZsSK1SusNQXsVdUE5Demp3vjxwRGCtuBwLhSd4yQQu8Oy",
	"9Di5ihdgmU5ARInQGi4UsiHft6tmz0XUQW1widpgrFPfp36aBlbRZM3x03zNC6Yix9AAgGljFEAlpFe6",
	"u2ZHAw98YGcjFdzcMXYGWupGZqoygQFM0tfTdILttEDFDdQKi5Miy0q7RVn75Gj+hqsToyhvVEFxhS2r",
	"Hv6Pwj6PZuhnLVFKouDbfnaD1/KRiVQwcKQS5QXYcvQrvAbNSK3XG/2l0gmkApwJgtM1Iu/Bc5K11E81",
	"c06m9c3AqAODBTR8/Dj6j9pY+ic7ngNpHLO2gxgDUb+ykrZgrcNKMiPLpRjP3OODox1QhlHMVJPARNS/",
	"FTTq3VSAdbAjl42rm+D1L8zYSwRZUKn02wQvyAqv9avjM/4REXRk3BQmsBZpfcvdYKCSybh+/CSyinAu",
	"VrJJe2VYUGsIo+T2Gz05KK378C+OqegbSYzl/MTD18Ry1bd5FMoImO6EtXZBA+k6NB4ir/Tv0yhQNIMF",
	"sUFN+jJYR+KiAerv3/3yv62AiyW1eFgfjkhSjZh3BRGCi9dtmeT07NAC2Vw5Li2b01zOMc0KEWd1uKAL",
	"ynDmM10OimUWRIn1gXuSq8t5U/FjNcRUYXlVFjjRvWlFJzXIo7QChfrK+063NWPDwx90M+/JPZx57ib5",
	"VE7/Bkt38OiSzLkg1n9lhcWVUWbmJWCs79YdUSRY6BB8+fEb2c3/1hoE6Q8x+rG4JIIRReTucU7Y2ZLO",
	"ladVVR1PNLTobZuI66N6yhnQ/slRi4UcklTlGV7HvSV/qOWcNG2RV5IB6rQTWI3QumNaYY6VKBp63599",
	"hSMq0Y/fyBIUVCI7SFznSd6b/Xoo7ncAxzVGJcwtbEz2Wv/dyOtPWm7BAjP6O5zNvpR0ASa23ie8UMvj",
	"eE+Tpwe2209HalnAQ+g76nH1jYy79l3i5I2MD3/67f4BnKvMcWIOtwyIjof2CJ6RzfZ/Wu3RsCmEQJg6",
	"LG8FeGMF0Uvqb8EZSQRR3dzNtjiL6UTCbEMdRYK7ajpGHMs0XbqlRrdSQspMEGhtrUAe3cYwgJRrjg4A",
	"KNU+isG4vqHizFo5/DSAUK8rnO1dHlIMdcBhMB4KWnK7KZWKskTZgiNTdLME6zNOlkgzupp+GdOEMq/W",
	"xeSKrF+ACf5iMrtg+t6+x6s8I6bIpbfZv8gFT4vEliDQQhlnLwq5Q7BUO88gzIWIF5c4uSIMeALPV/eW",
	"sK26QsZ2BxV4nWeljXeF34wKnF+DSd0Gs5dRm8jgtiwy+LDCKlm+MpVYTHSpSpalydi4cOy/OSTpDL1c",
	"5Wq9y4osq80uTTekRU2bV7J2M2qj9lGi1/X2UNTXr/RO1WdWONcb/+OKrKdwxh+Mn0W8ekwT5VwUZDTI",
	"VX8JmAjnamrt0mumlkTRpDyO0gYcemJozDXHcY0F5YX0HpuwDDlD+6XVRQv/YEQGpTY3mT7/KJ1Xp8gt",
	"7EM8ZwtlReTqvzY6BY0/NMhXr//GKKMr6tVSZdgZoLe3QxnHHupLJFYK/RAB0gNkHgEI+eLHYbp7SJGN",
	"/10QH/nslOuKIyolfDD6DVdIzqouguhcbJxNwQWVSkMWIGBDs67XRp3PyHvl7kpZhtmD+8CACcwE+m2R",
	"VILJDcbSy7IBvtb/kTiQ2Z1W7YF6387gD5XJBeT+ZwijOblxblHmTHMspb569tLCiTsHe2N+8FY/cG8x",
	"XjuwT3e0tcoBNDWsSeYgZSFtXaapgFq7kGaITFHBMiIlWvPCrEeQhFAPSmv2hVIerCq9tBgYV5gyyhZH",
	"iqxaxI16dOil1AfLlEUuu04AvHkwNYHS4LcWQFudwR202wqklPE9HbI4fVlqCRrkkwGvJkfZQDNbx3O/",
	"D7coiQoGJbkATw0g9TAO6BmZK1QwuDwsRXxFVeDPJYmgOLPcU3WhQQAZemyT0VySBBeSIAqfwcl6WTDw",
	"e+LlVwCBLcuRYWkbPSn3I4gFncHA+p7MRryb16124kLoeZaC4IAZun42e/Y3lHKT3oeoYA6D5Vo4YvoY",
	"9Sa8sbmON3pnfyFS0RUY7/5ibhv93bqpJzzT5weLMBVpfO4FPa8gQCnbxjY2PKAGwvvLWaXwkAjaxptR",
	"e86aTG3UZ+McTs7W2Q+pp33yQVsJery4DATuS22FSLxPVVktFggIvLK13NBHmrt5wxX89+V7/ThNppND",
	"TuQbruDvqCxjElK07MvyZqaNXsPKxSgP5ZFq/KIGYbDpd02wyy4m0TAwpTPccGtg/XBN+f8j0/VZk7Mz",
	"ZQGcse81Z1TxiOa7LlpAs37ZM3TGsJ36OfVw9HcxH9ohCVDDnYD37GAj5Bu8Iim6NqZIEBH6tCt3th22",
	"2wyPtRT8vHvBzTah4ogh8324rsjULzJUs1UxYgetNC7ZnDbdkUlMcpR2jmmzlxwddgxhZPMhw7TJh9PJ",
	"jaCKHLNsbTRMn6Zqq354fdotYENFJ2BME8t6zSkR6DEwsXMQ3CrffOU4w1x9rvotrts8b4tevaNOajqR",
	"Cc9JR54hC3fTzDD7zaqTvTI4nEDffTQ8cO891MITZXPeN5xrN2xEfRUOMkxXFRT/ZZKD8kqQ9FfvTtko",
	"7P3fZ8dvKqFL3rcy0SM6TtsvyHHS4PDEEEBJwxqGkGRhwgZsusdfLiJruJi8gy+a48rcH7K4vJi8e3KH",
	"l7+uk6xT0+Agq+cQUMcalbubQvP46PCg5wGptag9H0eHB4Mfjx4Cr4e6M3kPBvnciXsFtHci7XokS7zB",
	"OGEQ3yXwwkmiWQw5W3C+yMgs4avPlZTTNPl4hFxD+Y5k/IEI5X//fG4fg0+cQFqsvjfqV4bNN+me/6bv",
	"XlU7irMM5USAai2Na0iNwscqeiT0sCo6U+zStDVOLRE2mzFusjPeRYFcNgYNgfW1Dwq5NgCS2FJ453RF",
	"pMKrlignCJvUY9lchDdY2q2kFcVDihXZ0Y3jiatMibxN57LandTU3Bs+34KwIINxs9D7vwuwoFnVWSUT",
	"I/ZOZagcpaxODxXpbToKdMLzIoOSpQ7epvQqOiU43eEsWw/MoXbn6vWvjfXAJpi8Imunpzd6DIhVwCxU",
	"U9u7ZFTYCVZkobkTgh4DWYNfjUrnidc3T24dUWATjkYfmhtGopakIBMmVojfQJizSTYPv081hbuAxI67",
	"hkpZc1mLjreipY7GHFqdflh30stGMlCcP5JBBlSr9a4kVh0W6FOviBqFQcXYG0bY1zR1Y+bR7WUeHYbT",
	"/mzSzmOvKANNElL3njcxInjfmtrYMS3wmOD7T5ngO7wW0SxGnZl++y5a3E+j3qKauTv8Oibw/vgJvBvn",
	"MchEUiG3YzrvLzWdd4N8dF72pt4rlDqbd71fm4S8NgnYB7nkNy7FkYjDyjmTxtRnL52j6dGh565rCxzA",
	"e55glSxt/WkIznD3ZYO43N68GHqTNjFEqLnBqSkik2fG+86Uk4HEii0m23hWi30EKpATDtTMBwLGDb7x",
	"pZqrq3nrFJxe7KJmDeTjeVfyqDrh6EpmXn5zbhCWjBjhpUpHgmznplV0gwPKNT5M8EFXYdR324vsB8ns",
	"BktP6TbL3xnMGjvMU5JhRa9bciCchiV5hG1qXGbjkahtuNvs61w/nBLhDVdW+MXMhlwCnuj2TjPCr4kI",
	"cid4f9CJFMkuZSl5P/uXHEYSKqHwsX37rw5xw4reopKizSHEgiob6B09/9OO868klgtg/j1VIS5AKKGJ",
	"zg/D0Ed+bJScRslpt7xEm9VHCvptt0hSOXBc7Kp+rwpd/hsdy599AjKXqB3HIJEroPijwPWlClw1qtNx",
	"yRvBjVWX9CpTMSyLYT3vcG8GwzAxUV/jM7ks2/ZsvSUjdr3FZmmxqxC5Y1rq6mB3zU29WXpo5565nxGh",
	"TouMxESUYAdNBnpZ89SoZpCHLDx67HjoatFmHTx0uOd4XLoyXHYQB4evidAiWSGtFMcvbSSHjTeGibW0",
	"hr6D89zrTljbn4q2Kw3txUX617bMs9NJ3lNXq1pPy+zI+HQLulhoQhmDpDGcmmjFayKo6k++H573me3k",
	"Kx9XUtK7EYNjquyjavvsRa7KZM1sifZrA2ecCPMzFsx4Eh0IChEqk+nkiM35wDw2rWspB25tEszY2sYs",
	"Jdj0j9FH9NS/i/rZQOS9Ft5TdE0xbHv/5Cjc9IHGX/D6JGd0oZfpdEXTyUsmeJatCFPlbybP/MSVs61I",
	"duXKztYsmUwn5436GfuFWjq/sxZBseLMbfVupTbCBPNBviz9z4OTt60ELC9inuHTySGVV61p9Km8ivcy",
	"XvOtPvitPvUfPPG2msOKs/uHoY9dy276nrGudfUUFGiBhH4MW133mwcY5wvOwmw+hgCa5sYvo936jd0j",
	"EoulcP5O0AgJ3WqGjl1Qovk1hxBCSwmodJnKN2Br669ZhLuVeJVnlC0gRcd1rGaef3wuibohhLn9I+iq",
	"1/0A74nPad6RzrztqKfhUUR23EWsgTq00i39taoIqvhGQHypDVo0aYRsQqpSachN6k9w17O0EIRBOhrx",
	"RqXRqDRqEjN95TZVGwU9t604KofuL9xo4ph7MweZZuDNBRkTnCMflahCdwwGzKKue/qgqfoBy4iWX//q",
	"GEsT7AqNH662ZxRq7VmgegEGrSTk6y409dkcYF2GmQCU08oRVpbXhx1OsThS84+sHrSd1yzZmI8CXmBU",
	"EH65CsLaC9PJ9tWUhCaNQUYeyyeeqTO5Hjq1Yz11skyRuEZBDMoaabePdEvfwqTILTuU115hykzykxi/",
	"aZJqM65Rx/Wm+k6/xMnSpmCqDmX8z90AesEh09t9Vx82hf6QWl/Ok97X/GpC+r5KfUW4lG78u4WeNux/",
	"R00tvh0p7azb5RSWB/DituV48AwLWmpGxrtd6HW0ZP1yA3/fEYDhBw/iKyJjb1oUfqDC+SM5xlQmj3Jg",
	"jNwcx2Mh4IaSGwShEugx9RmBLzMCAVisyCAzkIs0bGqB9TXjheyYwDW5wyz2mfuOkizt4Awgq4oNSoGC",
	"W7ZfSQJK2uJR3Yf9wQ58xIyVGMx/Zr6gq/07Urd0YGxahS+t7iuKXM0C43Hrgn/FlvwGXi9o60uVamwK",
	"yvd26Tihiu+ZjWRqIwLVRk2lo6vEPFzjWBuxAxhhcvtIFWjz2ZlZXCXt3Pxar5tav6IQKGku03lZgrBT",
	"cVmURbPS5jENqBtcP1wTSSwK2Ne3Rbog/Yuot4d6M5Aw9HwpiFzyLO0bI/AtjLtx9VXhPjcuh6YCNwjB",
	"nNq8nbaQvHR71DeyejIhUauiQuyKncnllmp5nZ390FXKKxf0GivyI1mfYCnzpcCStNfkMt+NilQuT3zf",
	"T6MUV2VJvSWz7M4BQMOrZsUQJ7Rtb+YILMNj7jGf31N5Hr39mmegK9bTVaSnqzxNuasYkWtjHC2zSI2G",
	"WhWCWWlUY1uCs8w+fClnj1xtLGRSBQZhlqPu4n51F/ruRM6uWCwIhHmDP6k9HN3Wpn6gLuPlFD1FdO6S",
	"xdW51a+eRzWFo/Jiq8qLloT1QxxDSknNwNEFLLTIzljGPVBWOFlSRlqnulmuaxPog7Zc7sXkO5Mv/2Ji",
	"12NTLFJZZhklq1ytbVZESKpYFT3L3KT76BSWiZIMCxOv7Nyi7WYBjS8LTXmISc/Ir4kQNCWoRSMtu0mc",
	"Cz7xwEPHkOR1D11MzgxTczFBXIQ7vXe00Wz/DmbpjgVpL8mP6bDsxi2Z8BhQIl30QQCv/XQ/UfSaaBCR",
	"dhlySRfLnUxvCgpSQynVa1uVUVnFuY+WgQFhFRnHqfEYocz/bOoXTKYTNwg0SEnlzxWG/JWY2YCbuWY2",
	"9adhPizNve276ZufToN1Nr8elStvfvzO7aVlQred5ufD6n6bDV5XIBBbdQmT8jRfQhqentM0uXqqrnVw",
	"rHOaVY7SpQbySYJ2bMlsLc9SdgWfzD+CLzijWMIZStPC/CNooWemiZEX3QyUGa3ixCfDgJ+Bh6Ymacol",
	"Tjc7/wAaL/1WWr+d+vU1m7xyu2371NV53wKk+eW1A1Hbp65hzxwUm58OS7g2Px6VkG5+/D6AfQSngtNo",
	"fv1Wn0+Ji684TnswUV+8AXgoVXGpMY3jFBbGuNqZ8wJo3yVOdyRR9h6B2Q0In1gEuLcZ2viFn5l56z+/",
	"cuuof3jD1Xd2WfVP3+L0zK+y/vGlXXX999duF40PdlclsN8yqkoWv8aOl1SjV+CJPwr19C3RN6Kdi3F5",
	"yPThVqO+oDjJ2Q9O2EwxWZmHC79/RdhCLSd7z59+/U1r2rJNNlWnjR8MRm0yRBWlQRly6fvH0PvGvJpT",
	"2PqO3sSOz9ZTvpweHLaqfhUAf/+66u6Ed35/uvOPnXd/jfrP6olaaj7rqwWGE5s760KLjOnM5ly6mDyp",
	"ReQFH/slUUbr1R+rZxQCe1pByQCKMT6l7n3Z3Fu1QdXpKkx3g5x6dZRYR9+p0XcKetQuz2buU/XO2/Wg",
	"qo0ej7+LNKoG4dUajNqqj+9pEzuSQSbi+lMwOtx8qQ43MbLUd/cbsXmVt9+aitpZALDdxTkn+IRullyW",
	"A7j7PoeQI96vuDHjD9msp73D6vdaO1+8WO/GMXYbFq/t9NqwWL2vOrJnVgq2eeDeYGlcLoKMGUMyaW7i",
	"YtFIUBs9h83caPwGLO7N4HzpivwPd6WEXd30V9wEStXWoGHyO2ckyHIvbbAEzHa0/2bfpV7ZP325v/vq",
	"+GD//Oj4javHpn+s8sCmgpE+aS4QTwhm5g1xPX1xet04x0LRpMiwQJLqk6BqSa2/CxYET5GpHglSAtpf",
	"EUETvPuG3Pz6f7i4mqKXhca/3RMsqAtbKRheXdJFwQuJvtpJlljgRGmq6fZqqqPJIs+5UCRFjy8m378+",
	"v5hoEeXt+YGVTBrk6ZxfERbkBIoVl7CphIWP/Ipl/f6Vpq39Lf0uTyOWs/v9DjfkNSULwnbIeyXwjsIL",
	"Q1i4WE32gqk+tBp09itFKbwhp5KK/Vf4eSGwSRzS7eQycGk8JVO+0hc+V2u/vl+N7TfmgHPy48FLsz7X",
	"Zptr8RPXFgWb/lVF1Un2uKAJ+DyFCiSrQP4VkKGe2x4AGtcQ9S83WJIhPka39mshaOsaXSP09vQIPXb0",
	"qvOkEZ1XCnNVq5dY7H6yrTMId1E7giokY1X49WdX0QwyVAUdtou2laFr64SkwK0nAF+3tQwYrDJ97RUK",
	"cGQakIEoK2BImqkQ0UvTbLOGQAO2rLYjcvVvoJEZKp7TDZSSbd1NkToNl/bOv3bqDCsDBZ9aEszlVBD5",
	"K43pf0zlEN3C+mbqd4UyF04YD4PpQWR/VQN8jvsO6y8tNMmsrE6MviVYRMOGY04uxmfsLFmS1OYcqDvo",
	"lVKptK0cJeGaVUlQym+YtXDBs29YKhkWylR05b7y3DjRABStW18NvXrdxg4EZ9VKXlJhob4XOCGHQSaD",
	"of5vKmCgOuVD164hh8QZ77eSiCM25x0X7ujwALlm7Teu5a687L4k8bTN3xVZBmra3jIXEZZeL7WSXnF7",
	"yUUjJR6abIFr42s7xA31xWXMmcVI2l2cVvSKBMqb6qlct2l1vqcqFA7jhQdaRAo36Ds9c1AZrVn4tVmA",
	"zVxMW6FtaMSHGScPCl+7apvCxGRYvhkGN7dXVhX5u0Qlu2xB2ftdvZxZuid47z7z1urSkiSFoGqtidLK",
	"rPwSSJommeVf3zlx7b9/Pp/oB1m3nuzZr+X8kGzPYHZb9Z23b+O5QyuZ9gM/bIRe4xy0aLVsqGWtjJlD",
	"Tv2iTKDUs0t0vqeXoh/o8g7k9EdiH3YtA7qKvziBc4cyI5O9iSJ49b/mGV0sVaKyGeXliHoX38EXqIEr",
	"eIbOCV5NrIfgxGl3Kr0bRRN+qQ7x7nGs2xOr6DIIbd1kkwwLk71xhRlekBVIg3Oj2QDZlaQL4t26bfVV",
	"KtANF1f68ZCmfndGE2IJpd3Zfo6TJUHPZ08bm7m5uZlh+DzjYrFr+8rdV0cHL9+cvdx5Pns6W6pVZki8",
	"AlytAWn/5GgyLS/y5PoZzvIlfmYLczKc08ne5KvZ09kzG0ED+LiLc7p7/WxXs8m7iXf1XMQUPN8TVS/f",
	"0ygV5X2GNIaClGY9LaFOA7wJMO/zp08dbthSPjYkQffd/Zd1yzIUd0ihH+d8+qGBCsc/ahB8/eybrc3n",
	"tffNWt8FRH6VxIykMPnzfzzA5Oeco9eYrZEV9I19wbDgv0yqBzd5p79VDt/VKWs9/uoL71NyohPB37sq",
	"GrWa2CUY2uo+VepiQ73vQHUURyi3hPtEqQa/E4H329pq4aSfPnuAk37LnFRr8etPidzTyd+2eOLtUx85",
	"o5KxZiDjg7LR3brGGU2t80P0bv1kG0AZr+pN8QJV8ya4XkDQBV4RRYQELXiTM4iNqi+fW5p/4ZcEp8B1",
	"uGcrVKA49gRHCheZREH3dCG7MEPvBLZhbuBDTPotTh0mPty1NzulrNzreO8/7Xv/h3vm9F36sOs1KDnv",
	"1cOT9yZNRuyhDRX1coO39vHJ/mtbQfJJU4lqtegZvzHSEmiurcgUpz/nVkncSXzeBAHoHUxAIUsSBBKV",
	"J0AhDCeh6GUUkT30CID0LU/XW8OYijFFH3k41Pudm5ubHc0T7BQis6Fctx77Q327H+6RxFY1qq30x6t2",
	"tkxse6ev0NwNbqHDH9n6+oK7RZipsJpzoYr4unHYVvZdACg/Z1WFvqFGeZClfY6HIlOBZ4Rx85yhspSF",
	"vUIwgh4AKk+usLIG4UqjR8aQWZBHJiTb6UN8JDj4/LiTbBPu3SCdj/40VoTRxGrbhGxK0MTYfzOfQEYV",
	"gvnqatLWWKQCmdjvGTo0xl8gbuSaiLVa2hIZsYVCr7MgQvyBVmvC3aeOSFK2sDEzXGgQXxH06MWjKXr0",
	"Qv8vZil69B8vHpU+pVdk/ewFnNuz6RVZP/8P88dza8WN7RRmvN1ONSat8Hu6KlauOqbJ5QNw9pu0mFJF",
	"EEBD63kM9SkkUZ2IVumO6LyK5VDwwgzq+lv8XWGALZSzdLb2FGEZXBzI/ieLS1PqU5lb1IoZdAXetiWc",
	"eqP57pWNDQkHuOm1Kyy+XD62Ib4+/eoBZv2Oi0uapoR9dOb1IXZ7ZpWab5kPJWw8mrnPy/th2sKSHkA5",
	"YC2VRp/H5utoOlSy/t4PF1aZYhCn9Owe545BLR2v8b1f46cPcY0POJtn1JjQRsJRJRxtvPbuHyDyGoqS",
	"ERU1yOvfN6AtpkONtvQqvsIEaNGJNONn1tgigN5O8HxwRZjjG/40d//rB5jyDVfIRCqOlz/CNbTbCQff",
	"6u+JupcrvTDZOz71+9zHS4y3erzVDy4LYJVE/GugsuwGNxva38vdhgVu9XYPFVB2YOq/bnY0lZK8D6zV",
	"HUpfRjHlyyJqo2T08cloEWGOjJvyBlT01BSuvhc6Wibzf3BCep+anoemnqNuaSTaI9H+wtRZSVkoT5pC",
	"ec7jotuO3Fpgr8+o3NpxtDCPFubRwjxamAeRwlYqMpqbR3PzR3tmWx/TAbbnAS9qmx26q9jtfYgq7fM9",
	"sIW6ZyGjSDGaq0fCM4jZH2DITq0hOyRUyF47VBKcmDG7i0BtpOLpp5GjmXtUQ4wGsS1wK1HRXxCcGrHa",
	"yxRJx91umMAfmBBszTgOaXT/XZAjkzgB+JqPI9+MtGKkFZ+eZNNpSb+VZAN9H5hcjPb2+6VPo9A12nFG",
	"Oe8eyXARZdnAsF7j2g4Gc23WMP/ApPizMNnfUQ/2UanxqIYbX4TxRRg1f07zt4vzXPBrDOVJow/JPjSA",
	"gv0pYesuvr7Jzht/sNYO+27yrT0miiNcXfD4mIys/UjIR0L+eRNyk5ERQ3VzuSuILEze1bhx+RS++zSO",
	"l1iSFHFm3INKjx3M0l1u3XD8rzEfXT2aKS8h78m2bEY3M30kAlhdQnumlpH2jS4l904WKvd98m46eb8j",
	"LnHiyjjCGEZYNokiQYIGay3cUkchPjRpSI+Dp7kFfd6cJTEYXTdH183RdfMLcd2M4Mgl5xnBDM0zvNB4",
	"YquPIM6yNaxmtcJiXa0aJWfoZ70TABVHIFm5zNwGLABJm7/cDAU33w4WJsk1pYMA4PyGEfHIYFMF7x+V",
	"MKqXELrR63hkB9ZDPUJUwora4Ba0jWGZhcc9O4gY+jo6tY4cyEfmQIZ4sNZYhjZ3VdPsXuWHh3ZEDWcd",
	"1d2j1+mfjDI0ZYsNEiP1kw3T0pONjTTEtcFH99BRBTq6fG367rfnP+q/vN8TtbWb+5kkO2rnBsZrO17b",
	"B2TXu90ye68uNNza5R29K7dIQEZJYrS3jsLLtuhkVwajfjJpPSS3Rig/C9/HTfQsD0cYR53OSIlHSvzF",
	"qZF2U5Lw1YpKX9c3RrF9uevSAGXUPUHfpmqp/LhFBVM56GdBxkMojLzuSGFHCf0j07sMSyWJqaLXqnwD",
	"JwMsFdItoTy/VHiVtxCmDs3cKyzVGemvcTdMQ9e6rrnxKfw8tHceJh285tfNc3nDoVS1XsRIRkYy8pHJ",
	"iCAsJcJUZuwkI66hZZuitOLUttmmNj82uXN6stUzt0g1ov5gQKmuGL9hfiE/mfLybY5B0Pi02nbyqdoa",
	"Rio1ipMjXazRRWkG76OKppmmYJvYOe3KR2vnaO0cmaBPxdq58XUObJ9bu9CjBXTUCo2UbKRkd7FHbkzI",
	"KtbJrZGy0UY5kq6RdI0y3ick4xEmeJatCFMJZ3O66BTvysaVILOYVPfSNz0w425APfHAdFcmDHYOofiI",
	"SllUE6vO0NEc2fot6dQHx2oImQC6JUmuEO3LiWLj7GR8Eoing9hFKlGCJfEhftTp6Wx8ZB0iM3TEEM4y",
	"xNWSCOhrFhlAOZzIhEnCyi8JIqtctQYvJlJ8NNVa4+BHkj5yo38SAlve3GgWksbnnmQC5VUaWCWq0WFM",
	"MTCmGBhTDIzVoTZ8uceqUGMA/af4lvbF0rOOJ7Mtrr7R455C7JvzPHC0fcsCRiftMfB+5M6j3PkG4fib",
	"UR7TK0Z5NtIwt085BuyPMvuohv2sOJv2bAGb0ZaK7vVeCMtn4mEziN8ZCcyoFPw4gkxnloHNrjx0uudL",
	"P3rh3A/hGWWskZ0a2al7oK9d2Qk2I6/WF+ieCexn4Rt0SyXWR6Gto+5spOsjXf/zqetuUZMp8h40nwHb",
	"6x6egc+u6lJjC74S1cd+DtxC+lWKI4Ee1QwjubxVWN/dFZK386gf1ZIjvRjpxcdTS96JDMSVlPdBCEZV",
	"5aiqHCngKNJ+CarKO5HcNsXlfRDdUX05Mn8j8/elCIvXep5WkfCUKEHJNZEI+0AE02V2weKBKWbAvmCU",
	"P028wxkXCnGREgHhi7a4H8Qf6A255H/VWJNHeoxH6DEjN5r6zqmQqnVxMHhlUakZCqqcymQynRBWrDQy",
	"YPgLfnw3vW2shjl/c276iFywRV8cz3bqLH7RUUz3qo3QxzbGeYxxHh/vKdIYWH1+5hkhfbGR3+k2ffGQ",
	"35mBxhjIMQZyjIH8csssH9mMC231lN2mga60rQSnNkerPDODfLzyxUC2xkd5fJQ/2qMMN2VI8eLqM9wW",
	"Ywmt7imu0oz9wLGUwaSjD9gYP/nnIgoNTn33D/jvh11FVnmGlWYIJeWsnYUH9sO1Rr55jIc/t61+Khv1",
	"qq35DTPck371G9O0KKnnAZG6ZWb0UZIYJYlRkhizqWg6W6NbIzs/svOf0cs9IPVBalMfNB7YlnQHtQtx",
	"53f8/p7xuuV74MxjToXRvDyal6vqgyj3LwhODevr3/1eGvI9USMBeUgCUof2SElGSvJJcS6DczP1KilN",
	"Q6ek3Mgprjr0mHZpvNjjxd4GiwCJj3ov7vdEbenWbjF46M9hnhzJxkg2Pq5hsjOBUi/pgHZbIh5jwNH2",
	"aMeoBx2DjEYz7ZZIZFcOpF4KaaOHtkQjP4v4oA18SR6MJI5uKyMJHknwl6W16su5AQryMuyzqip3BDku",
	"Ct8utvNeBeJRFh1l0T+xLFqvPTtcMt3WXR7l01E+HYnYSMRuIS0KIwRuyIyEouO2iNgoQI480Eg+PgNJ",
	"xzh2D0oekVKpKEuUd8A2fX1OhJLOlJRgnZO2LBOvzMwDSI0exfpEewIj7ML8IgRftVnjrihLO+mNy61g",
	"y9oPyauwj+Y0s/EC9bVwlq1NxICPeEZqicOogAW9Jsy0947u9+JFv4VVGgfyvlVu3QO+RDez3gdJVnE7",
	"6Ze8x6s8Mz3Mal+aX+BSWwvw3sT+WPrf65uTuWsAjvYm3cs1FZytCFMvcsHTIlHGgU6QBeXsRSF3CJZq",
	"55neACXixSVOrghLzcUeRkPg8o1e7qOX+0d7iwDvq28RFwvM6O+wjs3yGVV6zhA61rTNUAtZ/WhInCYf",
	"hSQCLbFEOEmI1PQlnpbiuLKqe+QMw4nGqzlezQe/muVLBUlbeA3x3c0Nf69eYEFyLqnigpKehDCnruW6",
	"LyvMaTjmmBtmjOgcIzrHiM4B5K+kMONbOr6lH43N9U/iekiClsiz2JalpWx6T6laggkeOF9LfebR+2VM",
	"2vInpBYtjPUmsVSD6IlpXaEnG1l/IpOMoVWjTWa0ydyGQeiIrxp0mb8naus3+TPxLutmG8arPF7lB+b1",
	"u2OeBl1n61215Qs9uphtmaiMYsjohD9KPtuknZ3BUINIp3Vr2zrx/Cxc2zZV3jwswRyVRSOVHqn0F6Wf",
	"sjbcNUt6Lb+m6dmaJf2237LtaPwdjb+j8Xc0/g5kCkrCMZp/R/PvR3wwy4dxmAE48jq2m4DLxvdmBA6m",
	"eHAzcH3ukbcfDcF/SrrRxmpvZgseRFqcNbhCWjbUm0QmGi3Co1g/mpFuxzN02oQHXWqwCt/Djf5sLMPd",
	"nMR4qcdL/eCCQJ91eNDFtqbRe7jao4146+RllFFG+8MoFm2XivbYiQcRUW8pvgcy+plYizfV8jw08Rz1",
	"SiPNHmn2F6XKspWK2ozFWr6VduigEFNDri3rS90biRpQVGm0rDw0Wjn8eQd9jdHUvNSFyCZ7k92Jfi1t",
	"6zpyHTssMtmLNCUkTNktzII6HpUPk6a1NxiIM7RfqOWJ4Nc0JaLq2xCMl9sGvaMdEKHoXM9NzuiCUbaw",
	"pxAdOilbS9Na+Celex6T9Sg6qKl50j2CBqBph3CiXMnmygD2996VvGSCZ9mKMNW1U+JbDdqhXp/NfUTZ",
	"ApFrjYDhcPqH3qVVU9yF/U1SrU2WYBMa4URwKVFK53MiCIuPbtKkbDJ6mEYkOmQlf0PfvtsSNdixAoeg",
	"/pHaHH/8WMFDMWDHCaGw4cgrYUd0NOLDuw//fwAAAP//mJ7WtdPZAgA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
