// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9jXLcNpYw+iqY3q/K9myrZTuZqYyqUvMpspNoY1v6JDmp3Uh3ApHobozYIAOAkjsp",
	"V913uG94n+QrnAOQIAn+tNSSYoe7VROrid+Dg4Pzf36fROkqSwUTWk32fp+oaMlWFP65T7NjmV7zmMnT",
	"jEXmp5ipSPJM81RM9uoNCH69ZIpQQfaF4pcJI/u5TlfU9CDHCdXzVK7I0/3942cks31JlIo5X+QSWs0m",
	"00km04xJzRmsg2b8vUya058tGeFCMyloQvb3j8n+8SF5f/LGjKDXGZvsTZSWXCwmH6eTmKssoet3dMWa",
	"I32fr6jYkYzG1CzZtiWCrhiZp5LoJStWGxydCdMxxpHnNE/0ZE/LnE1rE/20ZHrJzIBcwZILGHBF7CDe",
	"BJdpmjAqYIYPuNH9DmC4Nj4wyFOzgeILjSKm1LPgJlK5oIL/BqewrxRfiBUT2kz1vySbT/Ym/7Fb4squ",
	"RZTd/Vwvj8I9P8JJwv7OYLLQos0ySDonNNdLJjSPEFd8cDORryZ7P08ozSYXgYXLNGGbLfik2uOjGYT9",
	"mnNpzvDn6qqnDgFbIdRYQbnI9PLfLAJI7F+qNMk1O6Z62YTECcskU2ad5u5Q25bMecJIRvWyeSuy4DgG",
	"okVv04TolFAcJxWAyGqtNFvNyLtUM6KXVBMq1oR94EpzscCmNzxJyCUj6TWTN5JrzeBesg90lSVmX7vX",
	"VO4m6WKXZtksSRdNfPoYgkGW9SOCWSPNssRigo8AcJrKHMmvOY0TppvoMJ182DHNd66pNPdXmX523oOi",
	"u/3h/7hRcG1uyoNUaItINEmO5pO9n7tR6lueMNfp47S77QlLqObXiAemcQXxzI9N7Kmt77W4/pFKxIIK",
	"TrDyA41jbtrS5LjSpEkYKwfxWlxzmQIWk2sqOdDDK7beuaZJbjCKSzUlXJh1sZjEuRmGyFxovmIzYs7x",
	"iq0JFTHBHoxGS7LKlTbodMn0DWOCvIAGL//2BYmWVNJIM6k8kuS23YJCDgz1x2nYWQXgaE6h/uQUiNoz",
	"FjT7OJ2I4MNyVsVlfFEcNF78///v/1eFAUlSsZgSpanU5IbrJaEkYVozSVJJRL66ZHIKsItSoSkXRKTk",
	"Zsk1UxmN2GzQLfx9kgo2AFCHK7pgbeDuw/JDkXDR3vvi40X32Z5qqnMVJhb4Dd4MorhYJFUYWzIXs2uO",
	"IHHU41iyjFoicWpAjP88yYXAf72WMpWT6eS9uBLpjZhMJ4ZiJEyzeDihqe7An7Px0VtE41u5qsYnt8zG",
	"h3LdjU/eRqqA/jFNcsTc8vpUwf2KzbkwPB1gb0yuoQfJFYvJ5Rqeqyq1rl6l8MV4L/ivOcP7YGm+P67B",
	"fS5CT0ETv336CZNd3BHnESQNhA3BrU6CqlvHHanm7t9wpQF/PbS1jc0euWYrNYD21M6wvOtUSrrupZ/Y",
	"DfGj+5Zt5cjfNc46yIVKNmeSiYiFmCT7yTA1eMezJF2zmBwdHO4YGCWcCk24OUVDMc31mtNIk0saXZmH",
	"qnPuEC756+khWeo0X62oXA8kXUniA1G1k63vGU30cj2ZTl6xhaQxiwOkamPyVF1tOUdrE2/y1jYBylRt",
	"UCzXgC7XywOQ/Jo3h2b8RyYVAK0hdR4f2m8ktqQJjhV/YzHBG4KoxhWRjrW2z8Pc4C+e4IycMmk6ErVM",
	"8wSe1WsmNZEsSheC/1aMphzKJVQzpUu5E7gcfJNXdE0kM+OSXHgjQBM1I29TaQTWebpHllpnam93d8H1",
	"7OorNeOpueKrXHC93jVvu+SXuU6l2o3ZNUt2FV/sUBmZlz7SuWS7NOM7sFgBQJ6t4v+QTKW5jJgKy78o",
	"ljqC1X09beMumaxTelSvfXk4JABXWhMqmZN+Qd6uzhsWiN1iusiruWPXlCfAxbZsZgOKm+tlAb8QsfWp",
	"h4fBQbqR6+WrtaArHh21it01vO/rQij8Uxk6LQFhq1C+pIZ+pwIg4WlfEspXqknF4ffjVinzv06P3hUS",
	"pkEaaI8CpeVO8WL6iyA8Nkcw50ySp2y2mE3Jz+eThUzzTJ1PpuR88vx8cmFI98/nkyhXOl3hz6lcnE8u",
	"nlXOqoGC1QOpoqRB72PJ5vxDRUkzmUwDe8ugYaH6qewAWBa7dljXzvmkX59ipj/N58OmV9BwyPQ7AJfw",
	"9LpX0q4MTAs88h+fGBEuoHap4btGVUmJND1Yf9LQ2bRie7UpYR+0EZcUkWnCFJnLdBXEaJIb4YDQElPv",
	"juNmyl1AV4vuTSS+gL9gbcUfjCarf6HqDdHZfd4QofuP1Az8YEe5CeVqIVnuBV+mN5ZswXnCw109VPNG",
	"4MZY3KBtZp8xN3OuuKA6hfdtRbPM7M+sx+69g7J3U+PpJGPyvTIPZ8fjgE1ah1CGBelcxCm06FSnGuy1",
	"amw8FUNpBgk3AyboH6AbTENG6IbSxzZk6+4WxLnOLiSSzPByhBJlZHSqa5QW9OY0WgJeNknHkMfF9DQk",
	"emfIKwONVcYiPudRF9EvRr3vh2fwiu79GXKXbxjtakWhVubX/1oKDKiLD7ONVaMVUXmWpaDMIZepXpKj",
	"w1cHIBQcmaFfBo1ao4SzVQnniouAwPEDFzHhcMuhpVVLFyBzWoGT16dnxE2AYEUIeuhQAtMAgou5s+TZ",
	"N8sIMXGWcqEtQ8wNnVH55YobdoX9mjOlDZxn5IAKkYIWOM9iqlk8I4eCHNAVSw6oYvcOSgM9tWNAFgbm",
	"imkaU037ZKIjgNFbpqnppawabKgUhbq1dsnJHqq3HDtH3w03EmD3LQcZEfAicdKiz26o8cbe/40tGN8W",
	"8b1xIFsQ00c68Sh0wpwpUonNbjueeN91L9xTOkQASrNWjKk5ukwnV1+ptsY/fKVqjVODqC9bKSQwAPUu",
	"PG6VAwzrULO11fn+in/CYP4/MHBPh+bSexn8Gij72tehadj/Vk8MpzUeojuoKQ18ORP1BnV5slP63J58",
	"WVv7cKGw7rKyNWGwMfBgIbDes+2adgqdwdPr6lGoOWmS9OgMwPfFmogRzhVho1+oCwsuvtWyIrzcLJnB",
	"qmJdzo3G4dn9CUgWi4bqdhr77D66IRcu1LI8Kgd+xbRTUwH70nuGzTOCvmGAOVYOtGBg9YI5YBGV2R5Q",
	"7bbhyeDuQsfxDdVRQE8JPwPnIghLGICdC3IJPyvDSwi0J1ahmPAV1+FNregHvspX1t+EpJJkTEaGWV3A",
	"ZtFECaBFpoRYUz3MaaYaRoKOi1GB6Ky4MNNO9l4Umzcc7cJwcYbyK5awyJLeTlaDXrLk1DU2HXPQvJ4t",
	"JVPLNIn7BvDX9bHtIE4tZFsOxH2uiAMOPQFOCMBLRtgHFuWaxQaK7eelWufbr46LM/JCLTqIZ0bcMvwc",
	"F4fY4UXzHigtqWaLdd9oJ2mSpLk+dc3rqF6ME0LzA7PnOY+oZqd8IbhYnCBD3Nx5a9OKCscx1GhZJPbF",
	"j8q+JVt+sD+KfaOiZlTUQI/W2+WEElV4Dt1uGOy+LfVP6zxhXVBn86piqLXpSCweXUfUeTaDnr7292bU",
	"HX2uuqNu0tZ0WpI0y8AEneYiJhQNY2g/jMnB6cmUrNKYJehdc5VfMimYZorwFIBJMz7z+A01u34x61xC",
	"k7CwDxlHU9Mpi1IRq5B3JPRHr/yCZlzThMdcrwujnrcQM808lSuqkdf+4uWkyXpD6JGkXTEFwyWpWrCB",
	"GZhQjcjFlJOpDXitI5GFMTBnBs5ZmuUJ/HS5hl/3jw+JghtjYA/tQUo2N3K1yjW9TFggtAARKchVnoEk",
	"o9jfv9xhIkpjFpPj12/Lf/9wcPofL56b5czIW8fJLxkxL9Os4DU5S4Cjpz4+dDGsSBUqR3K51ix0cYCF",
	"lWH9xKGIEcnQX6XACeyDBB9I1a85TficsxgE5eAFzXmA2L0/fPUA5+QtQtFFSN5/D78Ta562dnx4E67Y",
	"mmAvb/9WROVK5VXufzNVgNlyv3vzAwCmRgodNleQYzPS1+IHXiIUzTKZXtNkN2aC02R3TnmSS9Ss5cXl",
	"hV16ISqqBe6Ez8vAs5D7Ydm0JfQTh2zKc9MScCQ1MngB80G3y5BXFJ8DXGPxDZ23UXXs3bQZ+UGkN4JE",
	"XkPJyD6AjsVT8ooJbv5rIPQt5Tbecxin4sbsdT71thDEgWKg9g2WxxczTXmi4AFJBSPUXDntjjvKpQQO",
	"RIMDjeVdDVKfeCStpnuiSp9JKhTMdMbb9KymHdF8xXCmYmm66Mti5IvMuiwa6pRQkeolqg6L0zYM0I4Z",
	"K8yJKEMvWgKDSREYbNsRjnfC8HUOOvQyzbVdcbG8sHfOJVz3+DsmGL7T4d3PHCszWxQtkahUoXFDFVA+",
	"dO/NM5zWf9f//mXwXZeMqqCgQp5eSs7mzwi2KFkHN+cTNWinAwVEN6oTCEuF66BuaAQLa1PtCqYhlCsA",
	"UJ5/52XpD5SpwGgKSJnOyZk0gta3NFFsSmwAhK8gNt8n0wk02Diio7Y6O1btVzd07Wc/GKMKzSY+Wj13",
	"iXXclyS83ThKN5lOzo7f/sgk8BgYE+I+IA2EPRsC2GwK+lp+mbD6H46mHFOpoOnpWkTwjx8Nn2taoO7x",
	"UBzLdCGZMof/3og/Nu4vY5Fr+jZPNM8SdnQjmFSwrmsesVfMSD5cGbnCdBp2EK+FTJNkxYS276m338a3",
	"6nZbn2RviNY2BSxbWxRAbm1RXc4Jy1LFdSrXQdAbiLd+aJyP/7E4q28TxrQ7BfgjdGp4Gt7Z4Q/+CeIv",
	"Q88R0XzOF3W3gWHmiu+4DnTvNXAX3P8piyTTt4iivcWs32udhboBDLLcncrbVJiDbgZQV9/rFTbrD90v",
	"dRspsZ36WVd/9GDoZnc0fXMnuEuZitcfMoNLYUZHpoKwogHB9xKeOjN2nCegteErpmbnwmzStuCK/PJX",
	"Yv//lz2yQ95yYaTXPfLLX38hKysRPt/52z9mZId8n+ay8enlF+bTK7o2QHubCr2stnix88UL0yL46cVL",
	"r/NPjF3VR//77Fycoj8qi4k5SKpTs4gd03CvEFoN942aKuvIa4bhgizNkovx2DWTa/jtmZn3l51f9sgJ",
	"FYuy1/Odr34BwL14SfbfmrP/iuy/xdbTX/YI6Opc4xfTFy9ta6WBC37xUi/JCmCIfXZ/2SOnmmXlsnZd",
	"H1xMvccpWvire/mqBIl5l7/yupyL15jIwkCOPN/5avri7zsvv7BHGmRlDiAWCQnLoZinXeqQOjcF2iJU",
	"+cYEg5qI893ARbdE7FXFXW8QLhAZQVAExrMaOtpgYnDhzcXh71VzWbZcKx7RxBtvVHKPFrHRIrZbMiDD",
	"pRvb5xa2rovWe9zI7tAMoBbtea5Kcdb3Y+pOswCyUrxucYeyfiJzpzMA16clj5ag+4CeZFA2BzMNJD8J",
	"0NF3xSyuDXGSdCGghkf3RN5hZxbOQ/Jx2p7QoZQBbZMiVwJ6NFXXdbv8DnXxuEX3U6QtMOflAbTY/CC8",
	"qobth141hQ0c/iwhg0AtqUUgq0EVTbl9SjvR1H/tUN3iKB8oIfwkGltRSHTndGg6s/RAFfnwNkAeePqz",
	"UouA8LIxRgEXOCZiJlnc+gyf2Abu4W0dt0+rXJ2nc5MqTVo5DPvZZzSssgR+jlIhWGT1CsVhh5yggFk/",
	"fBUmRPYzOXzlq6xqM4QRA3u+9Z6OGr4XvF4xiyPUjrRBZkM0P3xdyZYVUQGvpUJtMThn0YT/hmrNIu0Z",
	"kysuaDIt1ozuYabblDAdtR0XjY9Esnb5BiuoWdvV1ANg+1H6cnMTEG4wy3dSh1JxVdou9OGNM9RULpge",
	"9mz6SzmDfmFlHw45bEveOE0yXhiT8LIoM0Njayuml2lcvVK+Cuy9YKDwAQVXpFO5PmFqcK66rhV7I3c1",
	"q85aQOHQvIOS6/XBkkVXbQSpvW399lZJFnc9SGS6kIxJcyPQJn7LN2An+AaUEk99TlzRHUh/++ZvR/tb",
	"R+rRIm8AzBLrXPKv90I56d/XsRYqvk3wMLSBcqauNv4a2tsVq2tvUq67CdZWnbxlTtpQtHF3s5oED7NA",
	"rhK9vj3SgAPTpixOid7A3pSL7mFuTOsCVs33ka8MJ7jK3N5rg19Dz5JHHWY4u9Wtssnv8Igca62z1V3g",
	"fOuL2VzM4KvZ+gB4yvQCv8PX81ZXsXYtWrbUdrN67nDz+pbX7g1V+pQx0fZouO/1hwJQTZkP2sdC2nr/",
	"ktaJmmZhy3+gFZQJ51ZhJENe86fpQOUa/hQLaMegN3zOonWUsO/T9MohjsOAb9g8lb7tYn+umfT+xgYn",
	"7DJN/RblD5tgRmUpjakDbeqraR3GX2DbON6am8C5ldiTuN5bEBjr6tFy8G1xC7W93o5RCA3SRoj8RMkh",
	"iDU5AjRAWmpQtYpVf9mQJNVWXScqtc+VVQS+h5bW06xKnoKO3uW3qlc3/j7G+T++D7d3EoM0Y9aYMbpn",
	"/9Hcs6cTqxQcdoKO69qeX3fIH+AV05Cr/BU6ajVV5ahS7DduYzvQLFVCwUmWyyxViMCO9natJFjDAGyV",
	"XCzAHaLjsszNdxfbuqQajZw1RnSoP2sN7h4kGgsaCu4TptLkugPcLhYamochjnssgvOpIqlpTJ6KPEkI",
	"nxOR4i+Qccr8aJ59pwELGFIf6IDd3oMHnEl2zdNcvd3koO0Zu77J2tq041seONgD0iRv9/T6Pr1xitN5",
	"wiMNjLW0G/MBgEZ32M1kOnmXun/Bvl6xlqzpnShXW1s7yh2pcKCG/9WrRgNqVtCOkaPTQjXcqo9aBV1B",
	"zyqDYIppNKDJlqIzta3iuJ2bug2zfHQ6eAs/Vo0BbhvhN9t8ecUXrSESMXyrj4XuF0Qt6cu//X2PPp/N",
	"Zs+GgqY6aQeg4LIteXawpGLxOJS9vobglRfspoPKCXZj6RrSu4K6SbZKr1k8jLg50tAxkWsSnk2kgg2Z",
	"qv3itp9U4f23EWIXzGSfmi7K8mGcRnUdTuUUc3V1l/4rtkqH8jqhEepO+1k+KQa1qxsK2m4cVxXfPAR2",
	"FanL/O8/UWmFrwPJNY9ocuts86GF+snsm1/LyUNfvQWFPrtFhr75rs7F93zFvNQCYW+uObhtT6hYW8/I",
	"qpbIzzRxUS/mAzFg3ueLaThiz4h3EpZTpNYoUnXDFMSlvjCi3m4qbXSZ+3VG9jVJGDXUWLCysaszY1Op",
	"xJUKTr/XVr83YWXpn68zmcY5mEunmjP59VxCdaPYSztk72B1kyE/Abcc3KWWhqnws2F46UQsFFCFx+0+",
	"1Yy8Vy7GzlZkW1HDH5LSubYGElXmJi2iKAxefo2TvZha3U+2pIr95etjJmIuWlOY1iC13T3C4MP2WEUG",
	"b49XbP0Cbc4vplds/fIv+MfL8IY+dhEVuBQqS4Vivbeijs3YDUVh2CYGyBTSvYd8CIXYCoKTvS8+Nn0c",
	"qi3a/YEK4BpW+YZJRmzGl3meJGsL8DjkENRwd6hM2U58u7jPeiXEDjfK0s1kWImYW+RCbC3f1BAMoqIU",
	"R3gh+P0Wawi6r4emV/2JnWik+XXp1WHdGTZVHTlnlWCAclUHubGbAkR4DVyHFWOsVAYsT4C6mKVVHnDr",
	"MF/NQDwcBjWX+RAUsERg3OJlgx+dhUXVnP1roQNGKjymWjMpVFfuIlRjZLZlZTMNamsTutl15IKjQmSK",
	"JdNSCf9Nc23zWU8JJv5ZsiTZUXqdMLJI0ks3GawfZqcLyoXSLqYxWZMkpTHDKWBNK/rhDRMLvZzsvfzb",
	"36cTO8Rkb/L//Px85x9057f9nf/ZOz/f+dfsHP7v5/Pzi7+cn++cn//1/PyfF//59H8Pa/fsn0/Pz2c/",
	"Y8PQ5//Vnkquq/wTqhqP04RHAznX916PIl9vG13s9ClpepGEDTXKqzxliSexfVcUzOA8QXfPSOc0KUNP",
	"70prrUTtk1yfWd6AwjQ9dAO3jDb9DDceveanOTx8uTgFzGIInrTOZ9NAMhjbS0Mqp1uGLPsvziCSXTpR",
	"gleFtVffyvfAuUtsx8ZMnr47Onu9h3aAIrCDKyJSTSTTuRSVcP9nA43SRqhapDv/VqnY4QuRSiuam8U7",
	"k9itTJQbvlFFn8ortanMu7F5oIHZSPBd9M2AAcr2XW+au/2V92Tje4+Txe8F1+033hp6NiG8cYuHi3fN",
	"K5CpkpVJmMr4R+nfpeJOAn6U6y1Pzke9Dv741s7j3m1bUhnfQJZe4aLYjDyBeyUVi+P2ncrtGlxOgW24",
	"lQdAcztfgY3qDIY9lI4gsDRcUtD3+ThOjTwVH83nFRem/RvKNcQPW79qDC4Hg8ExzdWGbgSVDXlLa3zz",
	"Vhv4WlUAVT41/VgqnyvbDHyvOzZUPoaAEWhWh095nBWyNiyo8Chzzuh4G7wcSuxDlqryvaELJvTsXLym",
	"0RIy40SplCCpx5groxQj8FpY34KIZvSSJ1yvZ+eiPzwRN1G5VVGaJFglurCNt7JnZpGtThfmPd5fQEVq",
	"bBK8hL65u2UMr4XhfzA+1sKpETxZjmxQJxRy8E2aanL4apOhMPpzyBPWCDg1b7Yjggjt8C6PCkp56ijl",
	"wOXVrfA+QAsoNFcxrR5fO91qSBI9/vcZtASzzIoKuii1SdZjAiqRR0kemy83Sybc786l5pKROL0RVooz",
	"74jN2hNw+bXtTjH4u5exws0UrYvH/bb9P/aALb6VcRDXtFU3Ov95tOmft/g8VjZ7u+exOcQGjnQlwAov",
	"uuwsfUUhVdRRro/m9t+e9+RtrCKVRXpTBL76swY719w4q18bhg9f1Oxhy5xi1QU4geGwEGjgws0ZejOU",
	"efbB/t8pgZeY3PbYDUheVFQy+73xFu2TS8nolbnRnTu5XJNzf13nk6ZLaIlcqs7T/gEWb9fUvXCdapq0",
	"GAfNJy9+NzTTwGRSlvr9kaBjpZcu6NQDyQBU0wCy1s+/tuEgNeLqqjfRysa5TaZ/sOQswQc8Kiso2gHg",
	"7ebqChMzNslD1lqDNeYSzF3rohCr039bfw1vzO69ZOFaphd4VjKHWb/JYxueWFNh1lpUE/uza5bYitPp",
	"DYvNsmxrJJMS8xsRDnia2SRHTTBAEdlv1u1KCjQBXrE1MO82LIxANwPiwrepnP8SllvRY3ha66c/7+/8",
	"D9357fnOPy5+3in+/a/d2cVfn/3T+zhA3wzq8feiqLjdUl0Cyzx4VMedkVer213qOAfMseADDXxHlQj4",
	"ut8zfa24xZzkojlvcY4bzR/k4XI/x5+rvvlcBetvusUVCXzdOooEBxgkrVNi6EXCNJsRuCRFHcqC8XWJ",
	"UcF/khLI6cWvbfwSM7fHjn25JhRVnbngekbK1EHFj5DEco/8ojALj8IUxFPyywp/wMQ65ocl/gAphAC9",
	"PVT7597PL3b+cXF+Hv/12T/Pz+Of1WoZxqvXIkoNUz8kSpfZtkjnIMgaCAPVtOZ+XykomlBuxFpM9Ds4",
	"xxtOdWw7u7+/sYN89FO9HRTa7Vom56LFjtUf93HG5ZintkOdsgXGDL1IjTx0Tdg2mnSU0rDpYA024gI6",
	"DTBjUMWYM+hPmDOocaE2Sx/U7L7dqhktaStDAkNr0zJVcFhjUBAKz4JISpLVniqCuvyXHUmpb5ZML5n0",
	"czCTJVXkkjFB3ADemV+macKoKNy6OoWVHqXnvss4jiOBOjXLkrUjLa0J2RqHZ/e50Ql5stYgcaL9qJt8",
	"fM+kfSfuWfDvevb7Le7nwJtQbfNM+ad/Q1Xl4IdFsrse36z7a/7ZtgPEJ2/Uqb+lgBQy3fAIbuFGEQB8",
	"cUCzIK6FQyqDzarRlY0mI0vw6HGWwTMZZNxuMo5j8OXnWhsnzLD00wDwe+Xo8Fo0ROrTaPtEuVAqcC0K",
	"RHaolliWUCUWv6iEwsTW/rsSeMSrvmrD0zdOJ6BNP+lLv3YGz1FnCjZAWZthavZvlQryNLVG3Q4n9K1y",
	"K66UgHNjgmq1HgPDVeH4tGSCmDvkPSBchdirFg7HnOcwZGuxcrU03OwVHPQolezvrZgpzxGvr4CJj8vN",
	"KiazjWuTNCtxsDvQ/K1VG2mqLzpO1zbpYjCX6Y1VgBkSDLce/H4p+Tbhi6UmB4Ykp4mPrF42mNp553pp",
	"yHJUKOk20sTs5xrKpnoKmJzvuFcofOzvT96403l/WN5CMKKTXKFDdSbdK/Z/TohBEeA+Ei6uMA82zOfe",
	"zg6Hg9uqmNo0TTV4lRO0wmAQSgAc+9HCNKvWFbJvfHVZFaTBqq+3QA0cese7kjvh3JAH0NCrrvCKalou",
	"07/moJUE0k/d0s34ZM4TiPkhZ29OwxcfF3PF1p2L+IGtN5r8iq375q5f9haoNJc46OCHk4QBlMEl+TTX",
	"Ir3loXv7MkiVSq5bQV623XdN26HvcynFyKRSFrDtAocCe5ETNq8wEI84lkwV3h+9GydPHVO7TJU2su1e",
	"lko9IFS7A0DFYoMnfx2sHA8/V3XM1o+AXaNzOtUkjcATvSjihk5vAWIejs+ri+9QnQ3MGAgLJMGSLxbA",
	"r4EcYSZH0wrKK66SfybZnH9AqwnjoHkyw+2Rp2D2AAcaqDD/zJvBfqW5TldQ+s2FzoQ5vVEw3rZgHJcZ",
	"AjpfQTOiyyYAQQbXkPYCtb7DdMMnbM4kFGofReJti8QtRdr28d6VyWJrAmg9V62BY2YLqm3RGtBeTk0t",
	"U6mnZEWjJResXKc9fqA/1WwltcJrSI4886VzDTnA8pJeoaUDW0CySP/oPrwvfPmrvzQautwttV/8MZth",
	"jy0/13ocHL9vBPEfHL+vh/0fHL9/Z572stFbyIrQ6Is/17vjr7URXnF11ehvfqz3Nr/V+nrxVlUfc+9D",
	"wzXd+1ZPevCKK8uq+Ak6A07qNZ/x+s9FviHvQ23UA4jb1w0PQ/t707ew6BD0KizOc6NyZ042rmFDS3as",
	"7rxSHXXAzC+H4tr+dmgfqTOqroqJ/R+PmVxRAXGe3h1oqX3mfj4UtPrBUvu4bFJetGads3J5ftmz8hb7",
	"v55qKpu/FkutDGCdQeq/f0N1tHzFVYZJo2pfLdRY4uDe6OqP61dyOzAXXHsnNqg4XAN25adgvTjzIxeL",
	"BoGq1JKr/1i0Ru/0E6Z0Klvy82DPQVzBKTb1alO2O9p5DOQRloBEejIlltb4lLwgNY4OXfTblLo1u1Wm",
	"JVDlclpUx8RNTS3j3Mq2ewmWAtz7jvU0ilwt1Kl52HJ45+Myk4nl59cZSF2VPEsYKJ5lNuC+kzp06mm7",
	"M//1EJYNRq4nuWvLTNUTWtmSx6rzIraM2N6jY1SPMgwdtuwSHnejhfassUafBgxY7REe1RKIAaNhy/Ao",
	"jjgPGMY2LccJvEyt9R/rLcOjNJ+yAQM2OpVjdz1rrc7KrV38cStvSDemBBs3x+pdV6WZJ925SG2so+8n",
	"NPs4HVgStHXwQZHVLdd/WO9uUnebMepErb84aRtybtKzFQuHVv4Mokd/515s7Rui44pv0nWzTXdSz006",
	"txDzjYe40yLC5PrjxUaZBoEHafFTcZ9qvinXoDkZHVIe3SGlOIhhXiigQh49Tz5bzxNP0AoKWMUqUGUG",
	"1wxyzhmJsqksq1l2XOd+A8GG8/QYTIp5Q3v+lidO5dK2Z/iIDgxzHqqJEXX1h0AHotkHTZ6+P/t25ysw",
	"TGDYQ2mbKieBGDo7Tcj9wLRzcQ/9VmUvjCMYHWO23150z3wtyuy1BEu1ZBDnCXuiMC5q6oXCWJMNRMS4",
	"5M0iXzHJI3L4akZeYYQOEN7ziUxTfT4J35I0Zp1TZ0xaHSgxbWfkv9MciAcuBkPxV+aqz+mKJ5xKkkaa",
	"Js6XIWEUolp+YzJ1iR6f//3LL+H4KLpZRXxlO2ApvlCfL18+f2aol855vKuYXpj/aB5drcmlDewhRa2f",
	"GTmcQ9aiAmJTjMSvbgaugNmnIrEHMLO8cNnVXLWmekdoQWbiezioNpw7cvp/v2hPVKjhbAZmLwPOsACh",
	"ytCeVs//+aQYu/KzE2Mu7Ao3CxX1yUgvB+bfub7G+5eQkp0dU3B0+b0ZUFlQhZbQSmD4AnfbBpP7hl/m",
	"50od+bMxhmiMISplps3ihrDLdmOFYMywpFV8qkpaWONivMmPLmmVBzFI0kKaPUpan6uk1a/GaYQtX0J5",
	"lyAPB5+ADa0miimD5h+mJE+H1SRk/ZtbTXlQGiyyA2CrepYR2PLAzCg2Gfkxk5GhUm21ZWwzw2vbdk4c",
	"u8Vk8zzp21jZ8i6b02yVGZrZGQrhy9Zn1Q7O/5kri0aGolvXZnDhT4P4o/mKxUe57tsktIOB7rLHWyfQ",
	"GT5LV1mkOoyn9jKGUGta5LDxMKHAdQ9wg8hCU0H8WdAFz+4ZIgyPgtO3QYC+M+yn6vcO724SvEVIV3DL",
	"QNwlSIF0IHcEeB+gw4aMh4d2zWIefPVMczR59gEbQVoEqNhYMIPVDBLxMpfeMwjf7Z1ux9RQT0XEbNMD",
	"LqGw+WFXLXYPf8jWwv+g98lyQfd/k2qW1IeHrnPsCIFXuiaSarYIJAqwYxgxCFoU7k6ltxekNv7m3l+f",
	"6pNz5/emvvMBxxgM42y22SyCs8FB1CwhGAL5TR9PYhm2ss4HkhUsT10DWGd2r1IzE95qR1A0bKU3ENpu",
	"dVjBjpNKYwgeKmtWdUqYlQJXHhK2XDL7tVZKs5k3spap8N4UZF5Vpka62LA2q5740e23FbE7MfrWqDy4",
	"sAm0nhIGFhKaJGvCS2nDuxpLes3AggMxaPhGQmI5QResEgHGBaHkZtlmUdwszLg48btXBYkbWWo3qSRd",
	"kKpBKq4qtdowrvk7Jpjk0QnL0sJY01UtLQsE6/d5KeHQziktly1i6NMsBbfqNdQO1ewZJP1Gt6ZhxWnN",
	"0LZNcK9cB8p4NV7nBdcnZjvhfAjW5QpjM7/julrAimDw4CapQV1CUFevmC8cBSq9uoKcaQmd/ue1HKpQ",
	"XYa5XaDjJ+yad+WEwK9m0bmrlNe73kaVumLxjVmnbUlOpxMxiOevVXnrX41AJtqefGji79P0aj9yxtbS",
	"nlnLSD7vLFeEpc5tQcsV04GMmJeMsA8syjUmpBhEiczaOqmR5iuWtumZ/tDpOskT9aSarfPJ6kk1WycV",
	"MXmyfHL3jJ0fQ5mBh7nQlthxkovJxwuwGVd/DKTQvP6RyrvkQnld1jol11RyCMe7YusdtFxklEsoLvBv",
	"FDNdGthcGBgHs2zLXLQ6La0MoKsY6lcuoGJNqFzkK+AccgUSrqYipjLGqnVErYWmHwzy8KLUKZ67Iivr",
	"xetmUiTjGcjGC0iNNzUYxeF6r7E8plsEyY3oTCi5pGpJdiL0A/oQVs3dpPLqFW9x4zAfMcWzS9aM24V0",
	"rJgBORfC2YHsQgeQuly0kpTy2u5tgmtFt2Oql0dZrwNEpc/rD4bBwzKPvevyGjeNnIKw4rNH3JjBPyip",
	"kBItc2aOrmBDwjTP5oBmcfDUQltu3Ke0xYuqiJJ9qp4RMz+4/FANHmQsSW/QOQheYbMFRTVX1rUJfi2W",
	"PtzyWHHOCRDkdm6AWleVgi1AfzkCKoACLQtQA6ccoev9HcEcyjM+NVAN4ojWWZkbeIP6ugcVbsks8vuz",
	"s2MsvmEoQYCNp7NIBt4uzFdMnPefTFNNDvaD+JNRpW5SGbcxYPiV2PQGqO0PrKuwfxTjhcLxrniGxt8f",
	"mSyyyAdSX1zxzDK6lmkk116HcLJPnahBwDh7c4opWZzP4aClm9Gv2Hr46FdsPXzw9KqtTCF82g70c8Vk",
	"O4/ovvbONcABr7wB3dLEUutsoDghcCXDBApDFY6DZMT86kQIlEOfKCQits6WTr2Eo85rtl7iEZaimMHL",
	"kr+7kVxrJu4sjsimOOKkCWrrh69FRDoEFSyKG9q8LDyA35+8QVIZpStD8ufapti9pAq+zsihJhEVlo1h",
	"5NecQYkGSVdMg8tNHi0JVXvkfLJrKOKuTned68Y/ofXX0LrNb7NV5CmO7+GlHIeRbXT9lrqAZeVJ6ORG",
	"ypZeKPJWdAiAtXDuKYlokph3M0pSgVJqEJMglh2rpLTglBkP8Q1ZwVQkWNDLdTXsL/o9WDm+PGooiS8V",
	"WUEuI4PgDjORAQY5Cd4uu2rHb16u3QFbjylizsIw1bASpiwfDTl9lizJkJZpTPZjd1SUptQ6K1yONtKj",
	"TP1zDWHM4YouWFuF9sGuv94AP6ZJvmK1Sus+c+yvlJvZJxd1n14qNZ/TSE8uDIdbc9tz35qGD58aG7Ad",
	"HRwS17xkqPxa9jS6ogvm3NR/zWmcME0ucxEnbYmRcMn9k9v8W0wS6NE1/6Anq/XwjvMkKVXzZXmPw/m7",
	"VB+jLrhR6MPVbqw6sT/x+zyZkZ+M0KSYhm/7yQ1dqyfojI974opkOZgrzEOzBuG/1uud+VLpBIwvTSSj",
	"8ZqwD+AcKFpKhOKck2l9MzDqQH94A59iHPNHbSzzkx3PgTSAww3GoMCDziDTcjSXvKF2V+0NaDvcSt9A",
	"SXM/X499iNH59OjgcAf0PZwKbSFvuCZ7HQIazgoa9W7KwzrYkUs41X0x+heGJgHJFlxpQ36BSK7o2hBW",
	"2rhUpqNIMfe+Nbr6lx60Dklq6LsiVtebypXyCQQOpPyaUUN4Abff4MlB9dgHIKr1eopQtDaQ+8m5Qvu0",
	"xzKOg4VibzVlkEd3Tla7oIthtAwaD2HJ+/eJOgLDQ0D4S5O+DFYDOIf3ugbgflm8VsCF8jY8rJtCIG9E",
	"yIGASZnKt23J0szs0ILYdDAu85hTzs0pT3IZFh1SyRdc0KRI5jgoXFcyLdcHaR4KUXxXcdVEYqqpuipr",
	"eJjevKJ2GeQ0WYFCfeV9p9ualODhD7qZ2uMezjxzk/xRTv+GKnfw5JLNU8msi8aKyivU12UlYKx70h1R",
	"xFvoEHz54StVp5W1qIhqAy/DHyU/5JdMCqaZ2j3KmDhd8rkuaFVVjRGMnnnfJsUVgSvlDGT/+LDFCAx5",
	"mLKErsMOgd/X0ipiW1LogQB12gmsQWjTMa4wx1rmDdXmT0URH67ID1+pEhRcETtIWK3HPuB+CyjudwDH",
	"NSYlzC1sMEFr8R1F0mctt2BBBf8NzmZfKb4AK1LvE57r5VG4J6aige3205Faomsf+o56XH2lwt5rlzR6",
	"p8LDn3yzfwDnqjIa4eGWMb/h6BWZJmyz/Z9UezTU5j4Qpg7LWwHeWEHwkha34JRFkulu7mZbnMV0omC2",
	"ob4Q3l3FjgHfKUOXbqm0rFRJwgk8xSSM3GI9GgaQcs3BAQCl2kdBjOsbKsyslcNPPQj1envZ3uUhhVAH",
	"fOLC0Y4ltxtzpbmItK2pMSU3SzCw0mhJDKNr6Bdq3zW+WueTK7b+GqzM55PZuTD39gNdZQnDOo6FWfrr",
	"TKZxHtks+0YoS8XXudphVOmdFxDJweTXlzS6YgJ4goKv7q3SWvX2C+0Oisw650Eb0gm/oZY3vQarsY3X",
	"LgMTCeK2yhP4sKI6Wr7BYiMYQKmjZWkVRS+F/XevWDwjr1eZXu+KPElqsyvsRoyoaVMn1m5GbdQ+SvS2",
	"3h7q1hYrvVOBlRXNzMZ/v2LrKZzxR3QlCBdIaaKcC/QLxnGaLx4T4bwprel1LfSSaR6Vx1GaOX1nA4O5",
	"eBzXVPI0V4VTIixDzch+aVgwwj/YSUFvm2Iyy99L/8wpcQv7GE5LwkUeuPpvUadg8Id7KdnN35QkfMUL",
	"tVQZWQXoXZha0HeFF1UAK7VsmATpAZJrAISK+r5+RnfIAk1/zVkR3Ov0xzolXCn4gPoNVyvNqi68AFSK",
	"/pTgZckVkgWISTCs6zVqrAX7oN1dKSsNF+A+QDBhDf0oFYorsCrBWGZZNobVuvgxBzK706rJy+zb2bSh",
	"+LaE9PaCUDJnN87zB880o0qZq2cvLZy48yFHDXu11D86psA+3dHWkuPzGFmTxEHKQtp6BXMJ5WQhkw6b",
	"klwkTCmyTnNcj2QR4wUorWUTqlWIqvTSYkNbUS64WBxqtmoRN+oBkJfKHKzQFrnsOgHw+GAaAmXAb41c",
	"tgCBO2i3FciaUvR0yOL0ZbElaJAyBRx3HGUDzWwdz4t9uEUpkguoOgV4ioA0wzigJ2yuSS7g8oiYpCuu",
	"PZclxSSnieWeqgv1YqTIU5tv5ZJFNFeMcPgMfsTLXIBrT1p+BRDYyhMJVbbRs3I/klnQIQbW94QbKTyZ",
	"brUTFyWeJjEIDlSQ6xezF38jcYoZbJj25kAsN8KRMMdoNlHYU+t4Y3b2V6Y0X4F96q942/hv1hM7ShNz",
	"frAILLpSpBcw80oGlLJtbDRTATWQhUuYVQoPCRJtvBm156zJ1AbdEs7g5GwpeZ962icftJWgxwvLQOCh",
	"01Zro3AbKguiAgGBV7aW/vjQcDfvUg3/ff3BPE6T6eRVytS7VMPfQVkGcy607MvyZtjGrGHlwnCH8kg1",
	"ftGA0Nv0RRPsqotJRAam9PcanoehfrhY4f4Qu75ocnaY+d5lxnybCq7TgOa7LlpAs37Z0/c3sJ36OXV/",
	"9IuQm+iQHJ/+TsBB9MjIky+79S/NNr4KRhD8PlzrgsVukP60qhjsoJXGJcPQpoXBLBaHceeYNtXF4auO",
	"IVDKHTJMm6Q1ndxIrtmRSNZOV/NhZ5Hu2FanLMolO/0j64/q59qnQgJeT3bCDJtY/mbOmSRPgVOcg3RU",
	"+VZUIEMO5lNVIqWmzcu2KMg7Kn6mExWlGevIV2Phjs2Qo25WL+wVdOEE+q4qMpq9V9RIKFzM077hXLth",
	"I5qrcJBQvqqg+M+TDDREksX/KtzyGgWi/+v06F0lBKbw0YvMiI6dLRbk2FVwnBEEoGRgDUMotkD3c+uP",
	"8fN5YA3nkwv4YtiaxP2h8svzycWzOzyvdcVfndB6B1k9B49w1gjg3bSGR4evDnrellqL2sty+Opg8LvS",
	"Q/vNUHem/N4gnzHdr0D9TlTfjGTpOhgH8E64HFE0igwvr2aLNF0kbBalq0+VyvM4ejwab6B8Rwr/QDT0",
	"v346s+/EH5x2Wqy+N8JYRmY3SWLxzdy9qnaSJgnJmATVVhzWUKLCxSpaFPSwKjKsp4ht0akkwJwLkWIC",
	"wLsocMvGIKFbd26vVmgDIJGttnbGV0xpumoJpIHIPDOWTXd3Q5XdSlwR/GOq2Y5pHM6NhFXYNp3Laldi",
	"LOs2fL4FE16S3GYt8V9zsGBZ1VUl2R8tnLpIOUpZAB2KntuMB+Q4zfIEqmI6eGN1T3LCaLyTimQ9ME3X",
	"nQukv0Xtvc1heMXWTk+OegRwh6fCVxPbu4Qq5IhqtjCMCyNPgazBr6hSeVboeye3dlq3OS2DD82NYEFL",
	"jpdskWqS3kAkLeYzh9+nhsKdQ+7AXaRS1lzVomOtaImDYW1Wp+6XNizEJuUprp8oL8lmWSG/zN05LJak",
	"XnQzCIOKsdUP4q5pysbklttLbjkMp4uziTuPvaKMwzyX7j1vYoT3vjW1oWPm2TGH9J8yh7R/LYKJcjqT",
	"yfZdtLCfRL1FNTm0/3XMEf34OaIb5zHIRFEht2PG6M81Y3SDfHRe9qZKzJc6m3e9X5tECm0SsA9qmd64",
	"LDoyDCvnzBnSrL12jp6HrwruurbAAbznMdXR0pY4huAId182CP3sTb1gNmlzD/iaGxpjnZIsQe83rFgC",
	"uftaTKbhxAn7BFQgxylQM9BntIV65i38HF5dw1vH4HRiFzVrIF+adeUnqhOOrnzZ5TfnhmDJCAovVTri",
	"JdTGVsENDqgI+DDO/121Ny+2FzwOktkNVQWl2yxFpDdr6DBPWEI1v24Jsz/xq75I2xRdVh0CDkkBth/o",
	"61wvnBLhXaqt8EuFDXkEPDHtnWYkvWbSC88v/DEnSka7XMTsw+zfahhJqERbh/ZdfHWI6xeNlpUsYA4h",
	"FlzbWOLg+Z90nH8ld5kH8++49nEBQvkwANyPdB75sVFyGiWn3fISbVaCx+u33To85cBhsav6vSp0Fd/4",
	"WGHrDyBzydpxDBK5PIo/Clyfq8BVozodl7wRXFh1Ca8yFcMS5dVT2/YmyfNz3/Q1PlXLsm3P1luSLtdb",
	"bJZ5uQqRO2Y+rg521/THm2Ugdu6R+wmT+iRPWEhE8XbQZKCXNU+NapJyyJlixg6HjuZt1sFXDvccj8tX",
	"yGV7cWj0mkkjkuXKSnHppY2ksPG+MLGR1si3cJ573TlR+7OddmU6PT+P/7Mtuel0kvWUbqqWbMIdoU+1",
	"5IuFIZQhSKLhFKMFr5nkuj+/u3/ep7ZTUVy3kvXcjegdU2UfVdtnL3JVJmsm5LNfGzjjRJifqBToZHQg",
	"OUSITKaTQzFPB+aRaV1LOXBrE2/G1ja4FG/TPwQf0ZPiXTTPBmEfjPAek2tOYdv7x4f+pg8M/oJDKDvl",
	"C7NMpyuaTl4LmSbJigld/oapzCeuYmpFsitXdroW0WQ6OWuUaNjP9dK5pLUIihVnaqt3K7URGEyXZbaw",
	"88Hx+1YCluUhz+zp5BVXV62Z2rm6CvdCr/VWH/hWn/aPBfG2msOKs/nHoY9dy276nrGudfXkrG+BhHkM",
	"W13nmwcY5gtO/Ww6SACxOfpltFu/qXtEQrEMzt8JGhFpWs3IkQsKxF8zCOGzlIArlwx7A7a2/poFuFtF",
	"V1nCxQJSZFyHyrIVj88l0zeMCbd/Al3Nuh/gPSnSZndkzG476ql/FIEddxFroA6tdMt8rSqCKr4REN9p",
	"gwYxjY9NCFUqDVPMLgnuepYWgjDIRyPeqDQalUZNYmau3KZqI6/nthVH5dD9tQExjrg3cw82A28uyFjg",
	"HPm4IhW6gxgwC7rumYPm+nuqAlp+86tjLDHYFBo/XPnIINTaszD1AgxaKUgJnRvqsznAugwzHiinlSOs",
	"LK8PO5xicaTmj6wetJ3XItqYjwJeYFQQfr4KwtoL08n21ZSEmEYgYU/Vs4Kpw1wLndqxnlJMWIesUXOB",
	"i0Zm50PTsmiBKWrLDuW115QLTD4S4jcxb7NIDeq43tzc6dc0WtoUSNWh0P/cDWAW7DO93Xf1YbO0Dykn",
	"5Tzpi7JSTUjfVzWpAJfSjX+30NP6/e+oqaW3I6WdpaGcwvIAXty2HAsFw0KWhpEp3C7MOlqybrmBv+sI",
	"wCgG9+IrAmNvWnd8oML5kRxjKpMHOTDBbo7CsRBwQ9kNgVAJ8pQXGXkvEwYBWCJPIDOPizRsaoHNNUtz",
	"1TGBa3KHWewz9y1nSdzBGUBWExuUAjWdbL+SBJS0pUD1IuwPdlBEzFiJAf8zK2qG2r8DpTEHxqZV+NLq",
	"voLI1axhHbYuFK/YMr2B1wvaFtUwDTZ5FWK7dJxQKPbURjK1EYFqo6bS0RX7Ha5xrI3YAQw/uXyg0DB+",
	"dmYWV6w5w1/rpTnrVxQCJfEynZVV7joVl3lZlyluHtOA0rT1w8VIYpnDvr7J4wXrX0S9PZQ0gYSdZ0vJ",
	"1DJN4r4xPN/CsBtXX6HnM3Q5xCLPIASn3ObNtLXKldujuZHVk/GJWhUVQlfsVC23VC7q9PT7rmpRmeTX",
	"VLMf2PqYKpUtJVWsvewTfkcVqVoeF33/GNWeKkvqrcpkdw4AGl6YKYQ4vm17M0dg5R9zj/n8nirAmO3X",
	"PANdPZiuOjBdFVDKXYWIXBvjaJlFjhpqnUthpVGDbRFNEvvwxal44sovEUzV54VZjrqL+9VdmLsTOLt8",
	"sWAQ5g3+pPZwTFub+oG7jJNT8pzwuUvWVudWv3gZ1BSOyoutKi9aEsYPcQwpJTWEowtYaJGdqQp7oKxo",
	"tOSCtU51s1zXJjAHbbnc88m3mK/+fGLXY1McclVm+WSrTK9tVkJIalgVPcvcoPvkBJZJooRKjFd2btF2",
	"s4DGl7mhPAzTI6bXTEoeM9KikVbdJM4FnxTAI0eQZHWPnE9Okak5n5BU+ju9d7QxbP8OFfGOBWkvyQ/p",
	"sOzGLZkoMKBEuuCDAF778X6k+TUzIGLtMuSSL5Y7idkU1DyGap3XtvCftorzIloGBoRVJCmN0WOEi+Jn",
	"rB8wmU7cINAgZpU/VxTyR1JhA27mhtk0n4b5sDT3tu+mb3468dbZ/HpYrrz58Vu3l5YJ3Xaan19V99ts",
	"8LYCgdCqS5iUp/ka0vD0nCbm6qm61sGxznlSOUqXGqhIErRjqzIbeZaLK/iE//C+0IRTBWeosAX+w2th",
	"ZuYRyotuBi5QqzgpkmHAz8BDc0yacknjzc7fg8brYiut306K9TWbvHG7bfvU1XnfAqT55a0DUdunrmFP",
	"HRSbn16VcG1+PCwh3fz4nQf7AE55p9H8+o05nxIX36Q07sFEc/EG4KHS+aXBtJTGsDCR6p15mgPtu6Tx",
	"jmLa3iMwuwHhkwsP9zZDm2Lhpzhv/ec3bh31D+9S/a1dVv3TNzQ+LVZZ//jarrr++1u3i8YHu6sS2O8F",
	"1yWLX2PHS6rRK/CEH4V6+pbgG9HOxbg8ZFBEvxL1BcVBTr93wmZM2QofLvrhDRMLvZzsvXz+5Vetacs2",
	"2VSdNn5EjNpkiCpKgzLksugfQu8bfDWnsHXI77ZTZOspX84CHLZwexUAf/+y6u5Ed357vvOPnYv/DPrP",
	"molaygqbqwWGE5s769yIjPHM5lw6nzyrReR5H/slUcHr1RerZ+QDe1pBSQ+KIT6l7n3Z3Fu1QdXpyk93",
	"Q5x6dZRYR9+p0XcKetQuz2buU/XO2/Wgqo0ejr8LNKoG4dUajNqqx/e0CR3JIBNx/SkYHW4+V4ebEFnq",
	"u/uN2LzK229NRe0sANjuwpwTfCI3y1SVA7j7PoeQo7RfcYPjD9lsQXuH1c+1dr5wsdyNY+w2LB7b6bVh",
	"sXpfd2TPrBRMK4B7QxW6XHgZM4Zk0tzExaKRoDZ4Dpu50RQbsLg3g/PlK/Y/qSvl6+qWv0kxUKq2BgOT",
	"31LBvAT4ygZLwGyH++/2XeqV/ZPX+7tvjg72zw6P3rl6aObHKg+MFYTMSaeSpBGjAt8Q19MlEIVLk1Gp",
	"eZQnVBLFzUlwveTW34VKRqcEqzeClED2V0zyiO6+Yzf/+u9UXk3J69zg3+4xldyFreSCri75Ik9zRb7Y",
	"iZZU0kgbqun2itXJVJ5lqdQsJk/PJ9+9PTufGBHl/dmBlUwa5Ant6afRksU2HrPuvFC+2Mq2gtXTXKfm",
	"GCMSpzfCav8AJIhuyi/ipfnKfU1tNXlYuXV5qPESvSb1A5mKapURpanU30kasVdelOdQ3wDtIVfn2+na",
	"NWh0mCh5LFF1i9dtvNJ3XPskN5zOt+WiukEvPmJBx1xyvTYnu8JJLxmVTO7n6BKJf33r6MF//XRm+Eho",
	"PdmzX8spIZsLZghvy/z+/n04OVUllavn6EPIW5opW+nd71AmY54ZSRvIqJkEavm5TJp7Zin/4p6Zm2b8",
	"B7aefDS7N0TGlXSjEeAT5LGe7E00o6v/PU/4Yqkjncx4Wo5odvEtfIEiZzJNyBmjq4k1QU8c+1Dp3cjK",
	"+3N1iIunoW7PLCeFZ2v9MKKESkwPtKKCLtgKyM0cn04gjixesMJvyJbX4pLcpPLK3ECFBRoTHjGBvhB2",
	"Z/sZjZaMvJw9b2zm5uZmRuHzLJWLXdtX7b45PHj97vT1zsvZ89lSrxK8Jxq0GjUg7R8fTqYlTk+uX9Ak",
	"W9IXtvKSoBmf7E2+mD2fvbAumoCPhpvavX6xS3O93I0KX4JFiIP4jul6fvhGmYLCKGUwFMJLrSkfEgFD",
	"KQmY9+Xz5w43bK54r9b97r+t3Q/v/JBM8s674WMDFY5+MCD48sVXW5uvEA+bxRxzcC3WBVxYDJO//McD",
	"TH6WpuQtFWtio4NRgNV0ASrh6sEhfaoc/jVNeGw1gMHj/9E2gFz2VTSANPfh43e9AOkkXTHNpAJWsEm9",
	"QqMa2uSWVlChJaMxUEZ3tfzqH46E0kD2boyWvSc87DoasxPYBuDDg0z6DY0dKuCkLx5sp1yUe/1TXrzp",
	"5G8Pcsau6L8V5QkaYDa5964WhGq996Dt8BMFVEMeqlfeNPbbqr57D9nfLTdaNDSXHqsGuxCLPNGeYgKt",
	"LH5hVsvzwAhmACj8gDX0dL3RE1eJ9ImtJWkdQwpH7GqhzhbWp6hU20VupqEaCLZcIsZDa8kjXdbXhPgt",
	"W0DVlbLAEgdc2nrRM/IKZS/g29g1k+uiynFooUmlcvPDrRa9zadOHIJyoLYaogHxFSNPvn4yJU++Nv9r",
	"+Kgnf/n6SWnSuWLrF1jz+sX0iq1f/gX/eGmFqNBOYcbb7dRg0op+4Kt8VamriohXbNKv9lpWcj0rK+tC",
	"ekgsI9qOaJXuhM+rWA75JnHQWsncFV1jtdRLVoi6UCC8vDgQfO8VqQUItWIGX4Gxq4RTrzPdvT6gPuEA",
	"LXk7O/f5vqDvhatlZt+w5188wKzfpvKSxzETj/5sPsRuT63I914UnnyNRzMr0uJ8nE6yNGSzOYBqPIYf",
	"Dj6PzdcRO1SS7qD6gCn9TRqv7+UmIQBKJYWWOfvYuMUv7nHuENTi8Rrf+zV+/hDX2EjeCUdd20g4qoSj",
	"jdfe/d28wB+RoiRMB3W+UGN9OG3BDjXa0ity+/HHwYkM44drLLgIiO8tmAj4T52+/PFEcMc3/Gnu/pcP",
	"MOW7VBN0FBwvf4BraNeiDr7V3zF9L1d6gcEzf/T73MdLjLd6vNUPLgtQHQUSmkBhlw1uNrS/l7sNC9zq",
	"7R4qoOzA1P+52dFUKuIMklUenr6MYsrnRdRGyejxyWgeYI7QE2YDKnqCdaPuhY6WufQenJDep6bnoann",
	"qFsaifZItD8zdVZU5qlXmKfeOYR325Fb89v3GZVbO44W5tHCPFqYRwvzIFLYSkVGc/Nobn60Z7b1MR1g",
	"ex7worbZobtqzdyHqNI+3wNbqHsWMooUo7l6JDyDmP0BhuzYGrJ9QkXstSMlwQkZs7sI1EYqnn4aOZq5",
	"RzXEaBDbArcSFP0lozGK1YVMEXXc7YYJ/IEJwdaM45DF5tecHWIEMvA1jyPfjLRipBV/PMmm05J+K8kG",
	"+j4wuRjt7fdLn0aha7TjjHLePZLhPMiygWG9xrUdDObarGH+gUnxJ2Gyv6Me7FGp8aiGG1+E8UUYNX9O",
	"87dLs0ymtqZ28CHZhwZY3Y+JdRdf32Tn0R+stcO+m3xrj4lOCa0ueHxMRtZ+JOQjIf+0CTnmq6JQXEzt",
	"SqbyFdhqwsblE/heJLm6pIrFJBXoHlR67FAR76bWDaf4NeSja0bD7I7qnmzLODrO9EgEsLoEnGSkfaNL",
	"yaOQhcp9n1xMJx925CWNXBUFGAOFZczMBhI0WGvhljoK8bFJQ3ocPPEW9HlzlsRgdN0cXTdH183PxHUz",
	"gCO2viaZJ3Rh8ATz0TKsz25Ws1pRua4mbVYz8pPZCYAqJSBZubylCBaAZKXUO9x8O5iX3thm7gWAQwXj",
	"J4hNFbx/UsKonsH3xqzjiR3YDPUECufKvPXqe21DWFbUG71XOzDS19GpdeRAHpkDGeLBWmMZ2txVsdm9",
	"yg8P7Yjqzzqqu0ev0z8ZZWjKFhskRuonG9iyIBsbaYhrg4/uoaMKdHT52vTdb89/1H95v2N6azf3E0l2",
	"1M4NjNd2vLYPyK53u2X2Xl1ouLXLO3pXbpGAjJLEaG8dhZdt0cmuDEb9ZNJ6SG6NUH4Svo+b6FkejjCO",
	"Op2REo+U+LNTI+3GLEpXK66KAoAhil1UVCwNUKju8fo2VUvlxy0qmMpBPwky7kNh5HVHCjtK6I9M7xKq",
	"tGJMdJZwxILsShPTEirAKk1XWQth6tDMvaFKn5rZtqKha13XHH0KPw3tXQGTDl7zy+a5vEuhkKdZxEhG",
	"RjLyyGREMhEzuFA9ZMQ19IqtN2jFiW2zTW1+aHLn9GSLh26RagT9wYBSXYn0RhQL+dGVSg87BkHjk2rb",
	"yR/V1jBSqVGcHOlijS4qHLyPKmIzQ8E2sXPalY/WztHaOTJBfxRr58bX2bN9bu1CjxbQUSs0UrKRkt3F",
	"HrkxIatYJ7dGykYb5Ui6RtI1ynh/IBmPCZkmyYoJHaVizhed4l3ZuBJkFpLqXhdND3DcDagnHZjuCsNg",
	"5xCKT7hSeTWx6owczomt3xJPi+BYAyEMoFuy6IrwvpwoNs5OhSeBeDqIXeSKRFSxIsSPOz2djY+sQ2RG",
	"DgWhSUJSvWQS+uIiPSj7E2GYJKz8khG2ynRr8GKk5KOp1hoHP5L0kRv9kxDY8uYGs5A0PvckEyiv0sAq",
	"UY0OY4qBMcXAmGJgrA614cs9VoUaA+j/iG9pXyy96Hgy2+LqGz3uKcS+Oc8DR9u3LGB00h4D70fuPMid",
	"bxCOvxnlwV4hyrORhrl9yjFgf5TZRzXsJ8XZtGcL2Iy2VHSv90JYPhEPm0H8zkhgRqXg4wgynVkGNrvy",
	"0OmeL/3ohXM/hGeUsUZ2amSn7oG+dmUn2Iy8Wl+geyawn4Rv0C2VWI9CW0fd2UjXR7r+51PX3aImU+A9",
	"aD4Dttc9PAOfXNWlxhaKSlSP/Ry4hfSrFEcCPaoZRnJ5q7C+uyskb+dRP6olR3ox0ovHU0veiQyElZT3",
	"QQhGVeWoqhwp4CjSfg6qyjuR3DbF5X0Q3VF9OTJ/I/P3uQiL12aeVpHwhGnJ2TVThBaBCNhldi7CgSk4",
	"YF8wyp8m3uE0lZqkMmYSwhdtcT+IPzAbcsn/qrEmT8wYT8hTwW4M9Z1zqXTr4mDwyqJiHAqqnKpoMp0w",
	"ka8MMlD4C368mN42VgPPH8/NHJELtuiL49lOncXPOorpXrUR5tjGOI8xzuPxniKDgdXnZ54w1hcb+a1p",
	"0xcP+S0ONMZAjjGQYwzk51tm+dBmXGirp+w2DXSlbSU0tjla1SkO8njli4FsjY/y+Cg/2qMMN2VI8eLq",
	"M9wWYwmt7imuEsd+4FhKb9LRB2yMn/xzEYUGp777O/z3465mqyyh2jCEiqeinYUH9sO1JkXzEA9/Zlv9",
	"WDbqVVunNwK5J/PqN6ZpUVLPPSJ1y8zooyQxShKjJDFmUzF0tka3RnZ+ZOc/oZd7QOqD2KY+aDywLekO",
	"ahfizu/4/T3jdcv3wJnHnAqjeXk0L1fVB0HuXzIaI+tbvPu9NOQ7pkcC8pAEpA7tkZKMlOQPxbkMzs3U",
	"q6TEhk5JuZFTXHXoMe3SeLHHi70NFgESH/Ve3O+Y3tKt3WLw0J/DPDmSjZFsPK5hsjOBUi/pgHZbIh5j",
	"wNH2aMeoBx2DjEYz7ZZIZFcOpF4KaaOHtkQjP4n4oA18SR6MJI5uKyMJHknw56W16su5AQryMuyzqip3",
	"BDksCt8utvNeBeJRFh1l0T+xLFqvPTtcMt3WXR7l01E+HYnYSMRuIS1KFAI3ZEZ80XFbRGwUIEceaCQf",
	"n4Ckg47dg5JHxFxpLiJdOGBj3yInQklnSkqwzlhblok3OPMAUmNGsT7RBYGRdmHFImS6arPGXXERd9Ib",
	"l1vBlrUfkldhn8x5YuMF6mtJRbLGiIEi4pnoJfWjAhb8mglsXzi634sX/RZWiQ7kfavcugd8iW643gdJ",
	"VnE76Zd9oKsswR642tf4C1xqawHem9gfS/97c3MSdw3A0R7TvVxzmYoVE/rrTKZxHml0oJNswVPxda52",
	"GFV654XZAGfy60saXTER48UeRkPg8o1e7qOX+6O9RYD31bcolQsq+G+wjs3yGVV6zgg5MrQNqYWqfkQS",
	"Z8hHrpgkS6oIjSKmDH0Jp6U4qqzqHjlDf6Lxao5X88GvZvlSQdKWtIb47ub6v1cvsGRZqrhOJWc9CWFO",
	"XMt1X1aYE3/MMTfMGNE5RnSOEZ0DyF9JYca3dHxLH43NLZ7E9ZAELYFnsS1LS9n0nlK1eBM8cL6W+syj",
	"98uYtOVPSC1aGOtNYqkG0RNsXaEnG1l/ApOMoVWjTWa0ydyGQeiIrxp0mb9jeus3+RPxLutmG8arPF7l",
	"B+b1u2OeBl1n61215Qs9uphtmaiMYsjohD9KPtuknZ3BUINIp3Vr2zrx/CRc2zZV3jwswRyVRSOVHqn0",
	"Z6WfsjbctYh6Lb/Y9HQton7bb9l2NP6Oxt/R+DsafwcyBSXhGM2/o/n3ER/M8mEcZgAOvI7tJuCy8b0Z",
	"gb0pHtwMXJ975O1HQ/Cfkm60sdqb2YIHkRZnDa6Qlg31JoGJRovwKNaPZqTb8QydNuFBlxqswvdwoz8Z",
	"y3A3JzFe6vFSP7gg0GcdHnSxrWn0Hq72aCPeOnkZZZTR/jCKRduloj124kFEtLAU3wMZ/USsxZtqeR6a",
	"eI56pZFmjzT7s1Jl2UpFbcZiI98qO7RXiKkh15b1pe6NRA0oqjRaVh4arRz+XEBfNJriS53LZLI32Z2Y",
	"19K2riPXkcMizF5kKCET2m5h5tXxqHyYNK293kCpIPu5Xh7L9JrHTFZ9G7zxMtugd7QDJjWfm7nZKV8I",
	"Lhb2FIJDR2Vrha1l8aR0z4NZj4KDYs2T7hEMALEdoZF2JZsrA9jfe1fyWsg0SVZM6K6dsqLVoB2a9dnc",
	"R1wsCLs2COgPZ37oXVo1xZ3fH5NqbbIEm9CIRjJVisR8PmeSifDomCZlk9H9NCLBISv5G/r23ZaowY7l",
	"OQT1j9Tm+FOM5T0UA3YcMQ4bDrwSdkRHIz5efPy/AQAA//9gx+ilBsQCAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
