// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1alpha1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9DXPcNrLgX8Fxt8r27nxIiuNzVJXKUyTZ0cWydPrI1nse3TOG7JlBRAI0AEqepFR1",
	"/+H+4f2SV/giQRKc4YwV7daLd6tiDfHVaDQa3Y3uxu9RzLKcUaBSRPu/RyJeQIb1nwdTwdJCwjmWC/U7",
	"ARFzkkvCaLQfXUDOQahmCFOEbV00IymgHMvFKBpEOWc5cElA95cH+7laQNVaVUGSIWz6YRTJBSCxFBKy",
	"EXrPJCC5wBJhukTwmQhJ6NxUvSdpiqaA2B3we06kBKoggM84y1OI9qPxHebjlM3HOM9HKZtHg0guc1Ui",
	"JCd0Hj08lF/Y9FeIZfQwiA7y/Ep/C4GtaiM20zDiPE9JjFWpHpcWWbT/wSBXQDSIPhU4SUFGgyhmVGJC",
	"gUc3TRgG0eehajq8w5ziTOHtg4PhsOzKfvjfZY9ljbJjA7qDSBUAlWoWOE3PZtH+h9+jv3KYRfvRX8YV",
	"AYzt6o/fkBRco4fB6roXkGJJ7gyZqMocPhWEQ6Jg12t+00JsA75jevcL5oZIaiQDVQFOEqLq4vS8VqWx",
	"iIPGOh3TO8IZzYBKdIc5wdMU0C0sh3c4LRTBES4GiFAFFyQoKVQ3iBdUkgxGSC3zLSwRpgkyLQDHC5QV",
	"Qipqm4K8B6BoV1fY+/YbFC8wx7EELkZRa9odFObQcM64bFOa+ooynOcKMELRjPEMSzSJFkxIVbhfEpT6",
	"NYnQcxjNRwM0iV7vvN7Zf70ziV7U94L9rnYolhK4Gub/TCbJ3/fVf/7a3hp1MDm7Iwnwyxzi/iQVWG5F",
	"LPX1xtV2W9OXrvYwiNQu6WAq1YBI1SoXbff//9//V18qlDI6HyAhMZfonsgFwigFhRnEOKJFNgU+0Ets",
	"UY0oQ/cLIkHkOIZRL17ye8Qo9EDUSYbn0IXudZvxhKaEdre+ebhZTYIXIFjBY3hHMmIOhCbXN+Uo1RUU",
	"MYbYX31V47xo93R4fm06UTQdMw6iotvdSaT+2Rn9z29btKs+tgn3+WQyUv+++CFIvRlkjC/bQJzq7xYO",
	"vfAFJbICZO/bV5mBZW8+iV6gQqhNeM6SDJcb8fn0++lSghig2+9vyZTYH9n3GZQ/5t/PXUljOmqE9nQ+",
	"TG+z+c1fe59RzeVbtXIxo0JyTGjf5UtLWui5vxtEtA7oS4llIcLHrClThyxGCvdpfV9bASGBO2K2oTt3",
	"zznk2B6pl2pbmz8vCkrNX8ecMx4Nomt6S9k9jQaROl9TkJD0P5brM/DHbBV6QLTKKqhaRQ7MVkEFd6vI",
	"m0gd0b+wtDDcsmLZdXQfwYxQEAhrjpmgO90CFQISNF1qQW8VpYSZ8TUlnwowPNhKS36/atsRGiLDNu37",
	"ooUe7OYL+axByUYs9pQVVG7RTo/X2fjmIbhYzbO2jm+DxsBmf0eE1JvG2yu2skIskZBtsqEt4VT7GHOO",
	"l2s3tmlmiHL11n4UOnvfIrBR6CzgMAMONIYQj7RFSgcxjCVP2RISdHZ4MlQ4SgmmEhG1lEo0UHt6hmOJ",
	"pji+VUfDyrFDBOzDs+ZsFpdFlmG+7Mkv09RHoujmlT8BTuViGQ2iI5hznEAS4I8b88Q6tNUYnVW8wTvr",
	"BNhhvUIJ7sMgOlQEM1PV4JLMFYe9gE8FiICM3VkVcU/NRdx+VMemOo/mFBIUV23RjLNMY/nwoE21OCe/",
	"ABd6xCYAB+cntgwllgdrUjLfIEFmVxryJqICy56DM7VnDNWM0CVw1RCJBStSLbPeAVdTidmckt/K3oQj",
	"8xRLNS1ClQyCU6PpGIE3w0vEQfWLCur1oKuIETplHBChM7aPFlLmYn88nhM5un0tRoQptpIpiWo5VoIz",
	"J9NCMi7GCdxBOhZkPsQ8VmJ0LAsOY5yToQaW6oUdZclfuBNoglv5ltCkjcufCU0QUetlalrFrUSZ26cX",
	"x5dXyA1g0Gow6C16hUyFCEJnwE3NcqWBJjkjVOofcUqUoimKqZaOLb0oPI/QIaaUaQWkyBMsIRmhE4oO",
	"cQbpIRbwh6NSYU8MFcrCyMxA4gRLvO5cONM4OgWJVSthD6ZVLTp3lz03I1EeEdt1Y5o3+au33yypeJO0",
	"kIdY7mpwW+T2D47zHNRZwAqaIKxOMT6MOag1RoeXFwOUsQRSSBQLvi2mwClIEIgwvbY4JyOPh4jR3e5o",
	"JQhtzgKfc8KNBAgxo0lQ/NftjYmjZBp3OCUJkctSEfAAUcMYFSfajwiV3+xVVKM4xRy4whZ8lhyvMtCU",
	"wkaL4urCRMtyozpGWBpaB+GOdoVeYwV0ONYMV+E5Z3mR6k/Tpf56cH6ChN7ACve6vpq5YmwkywqJpykE",
	"7DSGjoInxdUC0BQLePVyCDRmCSTo/Pi0+vvnw8u/7O4ocEboFMt4YTm5orZReX4QSBOl92KfHlYdQoZJ",
	"1ZZEaZOhfayPJf4+KCKd0MQQmYaJlzRh2hiOrznnpwKnZEYg0WJ7kF8UJMB7r0+OnmCdPCAEnocE4Gv9",
	"XWNdTUMfBqBF4ltYItPKm7/VP4gQRf1Er0nLawlYTXm9bPoEiGlwQkfNNeLYjPV1CPEVQeE85+wOp+ME",
	"KMHpeIZJWnBAopRIy1l6hjTRgXdEZpWRXwRMSlXV8B61XbZltEGFOMSUqF/ivNfuUuxVs7kAMg7LMiN5",
	"q5Vl/k4boZ+VdIpiryIHdKBRB8kAHQEl6l+FoTeYpAaoXupaOXhQTfOpwZtCkAbKjronWC1fAhKT1FiS",
	"GAWE1ZaTbrnjgnMtEEm1pk54VUR94bG0hrkJC3nFMRV6pCvSZd9V9ZAkGZiRStBk2RYSI6YpuCwZSoYw",
	"ZXIBvLbaSh4bqr7CgpFQ/KINxU9FhinigBNNTbYeImZPKDHTYQdPWSEtxCV4QYbGpnq7J2+Bgjmnw7Mf",
	"OUlmNC9rGqZSx8Y9FprzqTMrQUVuhvXP9Vcvg+c6ByyCmgp6PuUEZi+QqVGJDm7MZ6LXTHsKfa5XJ+S5",
	"nno2M/cEjR2geyghGIRIrkRAtf4rN8t6K0cNRwNNlGyGrrjStN7gVMAAWe3VV85VeTSIdIWN1fEGdLav",
	"xlfXdeNzTZOuYbNNj/YetKI64is23mwcp4sG0dX56S/AtYxhFHpXYHignrNigO2qcQxCkGkKzR+Op5xj",
	"LnTVyyWN9R+/KDlX1WBpygp5Qs85m3MQavGvlTZmLcU5xK7qaZFKkqdwdk+BCw3XHYnhCJQiRoRSK1Sj",
	"fgtxTDlL0wyotOepN99WWX26nUey10VnnRKXnTVKJHfWqINzATkTRDK+DKJeYbyzoLU+fmG5Vm9SAOlW",
	"Qf8IrZpZDW/tzAd/Bc2XvutoyHxG5k2Taz9r8lsiA83X2YR/LqX/S4g5yC3u+rYY9Scp81AzjYO8cKty",
	"yqha6PY1b/28zky19W4SlamFIdtovejq9x409q92TWjPxMySM3r8OVe0FBZ0OKMIygruqk8ddarvpEi1",
	"EYlkIEYTqiZpaxCBPv4N2f9/3EdDdEqo0l730ce/fUSZ1Qh3ht9+N0JD9BMreKto7xtVdISXCmmnjMpF",
	"vcbu8JtdVSNYtLvnNf4HwG2z91ejCb0s8pxxpWaohcSSKSCGquJ+qbQq6dsYzuxtqOqGULRQIJf9wR3w",
	"pf72Qo37cfhxH11gOq9a7Qxff9SI291DB6dq7V+jg1NTe/BxH+mrCld5d7C7Z2sLqaXg3T25QJnGoWkz",
	"/riPLiXkFVhj18YA02xxaa4N63N5XaFEncuvvSYTemxuZxXm0M7w9WD31XDvG7ukQVHmsBCSZYaxnNAZ",
	"W2UOaUpT2lpkbL4JinVHyG4wuwDBIZvqrtcJoYYYtaKoBc+63b8lxBjA28CZ73UTeL5YChLj1Ovvq5X7",
	"q5X7q5V7XAkg/bUb22YL+/VN5z5u+QO0743DNqqGOuvf16++mNe6UrIMn/7Ge8qqB8ZNTaD7BYkX2vah",
	"W6Je9/9qGO2iFeCj78tRXB3kNOkuJ5e2yttvzcKeKw+D7tv4Sge0VcqLbr3JGnBtdznfVI87bD/lnbNa",
	"Lw+h5eR70VX9zjV0qglTwdHPQl//NjwSAlfSdTIl9ihdSab+aWfMLY7zaSOE7wHxKAaJ1RfyTXyvxaqR",
	"w7sQeejZzyorgsGX2k8zMm+jjQNNgEPSeQxf2Aru4O3sd51VuT7OykkKlnZKGLbYFzSssUR/jhmlEFu7",
	"QrnY7XkLI6yfHIUZkS1GJ0e+yaoxQpgwTMtT7+ho0Hsp65WjOEbtWJuC214/fF9zPY4x1aelMNZiQokk",
	"OCW/GbNm6WIOPCMUp4MSZslcswECGXctF07OaLqM9iUvoEGajVkNPAR2L6WvN4f8Ke2sjdyJHUkldW27",
	"tIe31lBiPgfZ79j0QbnS7cLGPtNlvyl5/bTZeHmZZDaLUCO0ppaBXLCkvqV8E9g1BW3w0QauWDK+vABR",
	"g2+VIWkVxF7Pq6rVRy2xcKLOQU7k8nAB8W0XQ+qu29y9dZZFXAsUqyYoB652hLkT3/IMGAbPgErjaY5p",
	"IPoC1t89+e14f2dPa6zIGyCzojrnLnpNhdP+fRtraeLbhA5DE6hGWlXHh6G7Xgldd5UK7jZaO23yVjjp",
	"ItHW3s0bGrweJVFah1xuTzSKEDYWcSry1uJNBfQa4UbVLnHVPh9JpiTBLHdzb3R+p1tWMmq/i7OtdpV1",
	"lzZL5ERrmWdfguetN2YbmN5bs/MA8IzpJX2Ht+dWW7GxLTqm1LWz1uzh9vattt07MoN4GaewlTCbutaP",
	"oAY0jV5V5491BjTmuh37D3XSRV5+qGEIY20+b66V7BrX7zrqXzYktAbUTVJpFNegCJSHQFtTrUZ0ZyLs",
	"lOeXIlM0tYKbkQfR2WWpBnTKHlnw2v+q1onxBTfGEo6uL96tV5xMv92EcSa22kJnl72n8Etd8XPTCO4L",
	"XXJE5p3ucIkua/ZlTO1ILPDet6/28c5oNHrRFzX1QbsRVd4fboSu0tq67qC3cWvr2UEdDndoJUTcfkn7",
	"Kmhtux6abj95EZWdWuj6onb15Z6o3e4ZZBtbdjvE4B+Y241+yIkkMU63DjYIAerHMrRLq8FDpR5AoWIH",
	"ZKjMd5bw7MAdbKnBlPCKu5TK1tQvyCe3F7pbhfk0LpFb7o3GMNQNiCnfAobgHXZoeMHSkIFVu4M5bMSS",
	"3FWmHWvT6A9L3WIV9FKuH1kb2yq0m1dPOOz5ZmzfXaGdBwq02h60t+Z2RazDd38cNO7NQ1gwORmSDlOb",
	"KdSeq0Qx2vqNf8N/AMt4cW7iX4O2ZLeyuiKykbL1ybTMz+bO18Ghg3oV3xiYIF/G9b9KShTFbEY+D5CJ",
	"6FlAmg6FXKaA5imbusE0/Hp0PMeECukcG9MlShlOwAyhYcrw53dA53IR7e99+6oW2fthZ/gdHv52MPyP",
	"/clk+J+jif7fh8nk5n9MJsPJ5G+TyQ83f3/+b/3qvfjh+WQy+mAqhoqDkdDrA/jMvd05S0nc8/C59loY",
	"cn3oPFdWG5bapqSwXC+82EHLPJFtm2GtC5PU3PnEssBp5X/6pbzWilo+y/XPuw04TPuaLrDLcPuyYePe",
	"G5c1/X2Yy1XQmDTXae7iRmEy6ODrI/hL/Zb9E6cXy65uUrRpxSqtWxkgnM3kEoD28T+2hGHcbYE6/33L",
	"AdHz92dXx/vmvq/07iACUSYRB1lwWvP5f9HTyKLkojkb/ioYHZI5ZRyMpV8B7zSorTTaDc+osk3tlNpU",
	"bNXnyiZU3qJsw/CdC06PDqr6q840t/tr58nG+94MllxTIrt3vPWa2ITxJh1mLm+b1zBTZytRmMv4S+nv",
	"pXJPavqo4K1Wzie9bv1i+xtkb7ctME/uMQftw2Nc2Qid22VCNa+ax79ZtjC4wILHuFsOoGY709JGkeJh",
	"M+WZ9i4NB4VfwJQx63d7zu6BQ3I2m9XsmAf3mEjtRGwvV42H+SwlsTzHhdjQ6lSbkAdaq8yDNlBa1+Fq",
	"Rf6cAsW1aQbKm3awWmEIGYFqTfxUy1lja/08C89ydyNtdoMXSAmfcyaq8wbPgcrRhB7jeKHD42LGOYic",
	"0cQEzFRqhNkW1n8uxjmekpTI5WhC1/somknUdlXM0tTk3SodzTrFMwVkp0eDOo8P5jrHl6kS3IS+71hH",
	"H14NJf8YJ1mLp5YHZdWzIp2Q38GPjEl0crRJV8YFtM8R1vI6VWe2Y4IG2+FZnpWc8tJxyp7gNT3UfISW",
	"WGhDMagvXzffamkSay7hc11TG3IzTPHcxFxpvmwOJp3bLU6LRJXcL4C6785tdAooYffUanHqHLGhe4F7",
	"P1vv0niArxWszGTK2uXhvm37hzVoS7ayGhuYHvXWxT8eTfePeTzWJrvd8djuYoN7lwph5aVLfsWOsI4X",
	"PSvk2cz+7QWnbGPYrAHpDREo9UcNNm5EydRLfdslEbdrwz82jrgY/IuFjAQ5itXmNSsxHWhmQsStCRff",
	"JJ9pQjhoJ5syoakzyKnu632unsuK/JlHhR8fOsNFqnTFHSWUtyHK8GeSFVmV/AGnKbv3nWONg51kKLbp",
	"w0zyy7JBxS9dUH2CsI4IYGpj39m7b1BztH1PlwgbDVkpTCNUhZ2UH3UA9D76KEwEhzDpKwboY2Y+mKAM",
	"9WFhPujwk1E9Y97zH/Y/7A6/u5lMkr+9+GEyST6IbHETNH8d05ips6CPhxfYuoYatYOeXj4scSMywWcG",
	"eYqJkoZMkoje8YFmqHPb2P3+0XbyEAgTbIPfqrIie5GN1lcLbrzGVprGvoZ0fA3p+BOGdLQ21GbRHe3m",
	"j5uoqCOqGKc9WIOrWmVyCMtyJaPwbLuWY+icyp2evNiFJ6/IGXK/ALkA7qfIQAss0BSAIteBt+ZTxlLA",
	"1Nhmp5B+SWLoA5cQxvSkFd08T5dV6r+OeLnW4tl5brRClajeT67qXuq2QLNm0HUr7t2tfOnaH3R4jOjj",
	"H0sbBuSv/j0WtYXv52joWvzYFYNUD2VSdXvIkV6vA39KAXFssOESbHHBFUB8uUCjIK2FFehgNXPqeBXN",
	"yK26z4TzfNIXPgGXGcHDSxBKkuXn+xEm54BPU4ENXL9B7B9ZN4i0jnOxLjLmSpPiyugYfX5a5//Rr4JR",
	"9JxZU9uLDs/bx+ZULsuLu1zSbx94zIuI8jpqARSpA90jHiJCrLWDu6n17MXYumwPHRU32wGtTrpYjjn6",
	"tmKk3vXoutxSPi23E0yNNk4b1U6SBOEpP20iKP8RiCAeYlNo1mhGQr678ar2WlVCEj5L9Pz66s3w9QvE",
	"eDO7njeIjqMiaSeGVT2nOa2nA08RDJrW1PS7Q75UaRnk1Z73nLMiD89azeCZQLrGwFOmgWhZCLvs2/bp",
	"AeAkRidHI3RkdHwtqUwizpicRGF5mCWwcugcuHVF0pkpR+jfWaHVBAOMsQFnSqif4YykBHPEYonT6mkE",
	"rPXi34Azl1Fh59XLl3r5sDlJYpLZBiYQLNTm5d7OC6WnyIIkYwFyrv6RJL5doqk1DaDS03yETmb6urzE",
	"2MCYgOuT0dqtmqfigRXCFHjhoN9CAF+JLXavUyM++kJ10dxmBrdNXmqpUfS6yrXXf4LPupR7rsNAFU6J",
	"0wpGnxN5ocAIn8VeQm6M3hJZd2mzuRE3sc05i5yN/5yRuQvRrFIbdQSfu+L1QmbVVS13Z9sbSwtTF3BH",
	"VskjplQBXQgvx/RKeFuxuiXwrVEHXVbGVa+r+LNt+H32znxuVz40cEeKohbxLKTMe1IPRT9dXZ33pB+1",
	"98PvXqmvjmKMlPVMmCeo7EWrZJ5e406vpo+PBkXAHXDPsOq9W/VF1Mfb1OeIB9vgzCWN0Qq6NF6Rocnz",
	"8iS+vnhns5iyDATCM2k1eXWA60AIdCJ1eLO5gQP0qQBtEuc4A/3sjijiBcJiH02isaLBsWRjZ5b6Qdf+",
	"Xtfu4p+dFF4u39MTtaPI0Mgrn/bZ5iWljmcoesWAtB47ODs8CbxsEMiegXIc33aFi6jTWqx+xWo753TG",
	"ZchhqrfHWfCZnL6hOZ2r2fWgRzvkxjxxobl3helMNYcEYU+u6Xg+r1zGno+aXOopGoGwoGtj6k0jPZ3O",
	"qBzTUScuzos0rfyGqzupk9l7Js+Nute6nXJ+KnW56Znf5tkI/UMpskoNVmUH6T1eimdG/jN4JALlRZoq",
	"6UwnATOvt9VavVcltUb6QTCcmhQ0OtNwdwC1GTMaNCeje+15y6PwU/ajfjT6Up9sfw6lfV6B2ZYwekel",
	"tdsG3Lf9EDt75pjLnTVPpwRktxoZrZ2UR3UbvO6yHjCTn53DnAjJlyN0tSDmMmUKxiXKJDPyGprEwuXl",
	"tdrlrrOBOnlTRufqXyvFMp6JNu8V/nV0n2Nv1esxq5+D++NOHOOgtyKWwz9NrIy0zaFQaT6rLR0WoJ58",
	"vSuv5v7m8zSaqGQ21Xubv/SacakWBs6/P1aa6UTcIFqZu7RnyrHNwRxEQo/WV2WsoESmYSAASZ1qWwr7",
	"tUsMM4An0NvTPTiNfgipYA52oJ+f7O5FF6/tKrzyVfcDD0M36wzGtnW1SCHSMc8u/gnyzPaWDt/7z+1p",
	"dNcV1Q6q/RKhrluY8y7K227FZZmSucosV+ZV5jRFOXBB9JsaVZi1lrMW+A4GdrNYhVDoFmZcnROP27qG",
	"WQaM/JQyWYVobXmfUlU2mfFrkTrBBKnu3Y0yTcqKa00TK6W9Me6xcE989L/LTCCFbcay71/r5puMN1/x",
	"0MABEvCp0MzUpnGs+aLgUlhB3iME5XWZyY9lLgrRefNlE/eo9wXgZMhouuz5LsEXX6edYp3lxrrY3MJS",
	"VK8728u1Rk42xueYkt9MmEmMJcwZVz+fi5jl5quAFGL5whFzkIr6cXzrCxV8G+KehmzVB74vEJaI3etn",
	"VbSzlfk+UGfYRLuWjNVYk8jmq+7Ksqlbdft8UcRy/KkAh0Q9LNEJkUrvOWNZeyY856zqPrXy+epnFz/H",
	"Ml54fm+l1BSmgZl+TqHBPFjHTrLO6sbAalNp+ZofThIdDZWn5jDkkLE7vZXqySk8E0hQljhA/+vy7D06",
	"ZxohpZLfaq0JMQyq8QdTck2SKI3DAjVq8XaWr7LqNkXI2gvuKx/6R9xW3fyd/4NA20d94F/weExoAp9H",
	"v4p+VOWO7YMUuLywHvl5d0xNe0qLeh66hgOFNpupvsPeDEUX23WeveqElY7Xq3l7sia+A67UxUJY80eZ",
	"7nYKM8btwITOR+iN3ur7qx11n4lndQ/cZ9mzugfus8WzTg9c/WZ1p9NtDjwGKjuT6VTlCmtmRsbJgZP5",
	"XEkFIUyaE8loBHfQJ9C3tt6XtlE4gsD16C1TbR71Q+VmHXHVBmu7HdvSFs04FhRMmqJDfvoZnjphqTru",
	"rOKN2FnHgOJN2iWOUFMlaqoZodh+sEZg9efh+XWnF0P4HQoTotDp9NMRvuA0js4nnTv1kYeSuS3Ni3o1",
	"RUGdyb1eB+mYzdqnplfAtcb9qQMTDzcr1J72Aq6MwQpHTODajWdDfneMdlUSE10JcVVrhM5oujTviumv",
	"OXDk9qZ2ZDIMbOPEJhXHD6U2UScKofMTdU4HvWlLBj0FeQ9Ay/AO3VTB/QQ8twx56GK8KzTcgb8UgRmH",
	"GNqaF66IEQ9kwamVUxTgMU6dx1rC6DN3EYqMpdSTlr9GHPyxEQdx0CnospjPzQuY+kLaLk7s/Gg0/owj",
	"3gDtIGIdcIwVqcfbsF/DHB41zKHjGcI+Yqgf+qnw6HSertccOp7+y3C8IBQ6h7pfLBsDqIW2BtSJznda",
	"cKV+2jyc6MQCZEiACARZLrWBgIPJj1J3D73DJNVvnqIDdGHeH4xTzO0br9bFQzg/9wTQtFCcB0ymFSVD",
	"c5IAInJNGOqqXAkV8tCZfsRvH02iy0K/ejaJlF7mzfQPJxuRQzzENBl2pjbtEW1SvoSo2UTPtw9tPpMD",
	"nXBNoQi6bbMLMl8MUzUpkzxFZ2mr8ifVrlpNBjcNRcq016C+iCg/z1zuWteJrpBA7WeGFR+imFqdfcZB",
	"LPo/2Nee24Ebvl104cHZLj2pIG8Xlnl4OwYsXyZsFR/V59uucFrDQAjqCifVah5Ttb3WrCboSnWHZb2s",
	"zjvXLaWpmOgv+q8hL6i1RKaE3uoi84dXglOChV5DYWqYP7waamQSmyyWbgRCTdhtVNo09WcTeW4u2Kc4",
	"2Wz9PWwcl1PpLLso4WtXeedm21W0qvGBRUi75NShqKtoVbeXDovtoqMKr+3CkwrT7cK3Hu4DNOWtRrv0",
	"R5z4tPiO4WQNJaqN14MOhSymitKYTQ1DmRzOWKF53xQnQwHS7iOwGWIy4HOP9jYjmxLwSzNu8/M7B0ez",
	"4D2TbyxYzaIfcXJZQtksdHltmt9P3SxaBXZWFbK9tFQtKxiuuEbPJFfNQ6FphQ+eEd1SjHNC03HkNavf",
	"WQ708vIn90h6giEzB5eXhnHn5evAYQ8V3fWcVJM3PhiK2qSLOklrT8tp2T5E3vfm1BzoqQ/VJIblpUt1",
	"cpbo4AWl7gAsEfDqZV1xxMPfdobfDW/+HrTWqYHC0JRpNJ0D/yQSYpGM7NXZJHrRsMh6hWvFEj1snUrq",
	"a+Qje1AjSQ+LITnlimTwH8z5aTintHfMGLXaDyGg3xiF6jqDC6u0awo8OXh/4B77PLg4Phi/Ozs8uDo5",
	"ez9A91poVR/rcfdKsCNUx7BwxGLA1OiLrmXp+aezKWAuSVykmCNBJOgICmJf9sYc8MC8dGlwjA501AEe",
	"v4f7//x3xm8H6LhQO3d8jjlx5pOC4mxK5gUrBPpmGC8wx7H21XVzbURaoOeT6O3p1SRSC3x9dWjXtUUo",
	"161sNk2fsEo7t6+mGrUSF5IpgT4uU+9owxFNQkl7JMlcqYuz05CzIhQFtvZGvPHyqxH6uXzLcQx+Ro2V",
	"xjVX72EQSY+4VrUpibAljofv4P2b+/YzS20HAYNY60HQ907G9JN7Ti6VW5uO9bE0YV73z8skwtUWH4OM",
	"x3RO6Gelv8xGyT5n2yY1efDeQ9FwxHrqkGGSRvuRBJz92ywl84WMZToiLHJXqpo5vdEl6FBpUSxFV4Cz",
	"aBAVXDV1eletdeti+EO9i5vnoWYvrOXChl7qhCCgVFBztaWzUEFmA9ZmKYDUeiMkc+dBZK6b5QIIR/eM",
	"3yr6FyaDWkpioAIqf6noIMfxAtDeaKc1mfv7+xHWxSPG52PbVozfnRwev788Hu6NdkYLmaWGSqVergaS",
	"Ds5PokF05yxt0d0uTvMF3rWZxCjOSbQffTPaGe3a+0RNTEoNHd/tjr2gRxu+6wwqmuRYKEfJofGDw6jz",
	"vfGa/bjUtU+SsnFny8iQGQj5IzPPUXrhh57H4fhXa94wm3Mty+gc76FO2TbzqsmdJ8zG29vZfSpAQohO",
	"1FK+3Nl5NBjKFBatAX/ECSrhUYPuPsGg1xQXcqHdMexUv3mCUd8wPiVJAtQM+d0TDFnPEKnH3XuKca8Y",
	"Q6eYLt3S6gjpb58Ey5eGx17T0upnrvHxXOtandwnulHV1jOp8e+KyT7oGESQIccHnBjhpYzM6NyBbV71",
	"FuQqRlVFQenLw9U+Qet5JZIMzY1dnqgebICmPUXKV199TjXwFqip2haUfCrgxFypabZmLg5rjG3nn8PY",
	"zn7+k7GXl08wZGl4+MpY+jIWK81ZLjJ2aUM62clbkDY60+YXSdzz+l3izluQLmOJfaJ/Q75hH/A3vKE+",
	"uGje4T8O63hopyMqc+XrFCyo8WpwOawO96zGDeZrWTXuH8mfLPY7mdGe2aPNLYW88JR/Fr96IuaBKu7x",
	"JOLQv4Qg5PEMs5dXMojqcjHHMg4Hm7hAEi/3zdE6LqGb1dIdbcclfFFCQ/hYHOFmE7VsqIf++2arVnMP",
	"7qWUPR1v+Kp8/beQjtCfTjxCXfJRyesGUV4EBJ1rm/J7U0Z2YbzZH5mVVem6n5yXbcdEvrKuP4mg9C8q",
	"tlSpAvtbcykK5Z5ebcZtJ7T+Y/ZWe5wnNtt2APDVXPvf2Fz7ZzTUdgoMLY6yjuGss8y+Bbkpz3kLMsRw",
	"NpIuusd7VPPrH2vL6MWNvtpYv2oR/wymoIP5tD+/3o7mwnts0rSYdu1nzuwuF4jRpvyvnRXsJrSiTts+",
	"We+he4/7nbWBf7h5+K8AAAD//+w2vqpLuwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
