// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1alpha1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a3PcNrbgX8FybpXtmX5IsuNyVHUrV5FkRxvL0uqRqXvd2ms0ebobEQnQACi5k1LV",
	"/of9h/tLtvAiQRLsZrcVzdTEyQe3iNfBwcHBwXnh9yhmWc4oUCmi/d8jES8gw/rnwVSwtJBwjuVC/Z2A",
	"iDnJJWE02o8uIOcgVDOEKcK2LpqRFFCO5WIUDaKcsxy4JKD7y4P9XC2gaq2qIMkQNv0wiuQCkFgKCdkI",
	"fWASkFxgiTBdIvhChCR0bqrekzRFU0DsDvg9J1ICVRDAF5zlKUT70fgO83HK5mOc56OUzaNBJJe5KhGS",
	"EzqPHh7KL2z6K8QyehhEB3l+pb+FwFa1EZtpGHGepyTGqlSPS4ss2v9okCsgGkSfC5ykIKOb5riD6MtQ",
	"VR/eYU5xpnD10Y17WDa3H/6X68XA5oY8ZFQClQpMnKZns2j/4+/Rv3GYRfvRX8bVCo/t8o7fkhRco4fB",
	"6roXkGJJ7gwdqMocPheEQ6IA1Yt608JcA75jevcL5oYKajQBVQFOEqLq4vS8VqWxSoPGQhzTO8IZzYBK",
	"dIc5wdMU0C0sh3c4LRRFES4GiFAFFyQoKVQ3iBdUkgxGSK3jLSwRpgkyLQDHC5QVQipymoK8B6BoV1fY",
	"++4liheY41gCF6OoNe0OEnJoOOfsjiTAL3OI+69VAI9qFeqIxBWhrulLV3sYRIrWOrZjNSBStUps7P6/",
	"//N/6zhAKaPzARISc4nuiVwgjFKQEjhiHNEimwIfaNzFjEpMKKIM3S+IBJHjGEa9duHvEaPQA1EnGZ5D",
	"F7rXUfkJTQntbn3zcLN6bS8lloUIMwtTplgFRoLQeVrHsWVzCdwRgxLHPc455NgyiUuFYvPzoqDU/Drm",
	"nPFoEF3TW8ruaTSIFMdIQULSn9HUZ+CP2Sr0gGiVVVC1ihyYrYIK7laRN5E6on9haWEot9o+dXQfwYxQ",
	"EAhr6k3QnW6BCgEJmi71cVXn1vWtFN4Y15R8LsDsB8vz/X4V7RMaOgra9O3zTz3YzVfSvEFJi2BDeGuy",
	"oPrUzYxEe/bviZCafj2ytZXVHImETPTgPY01rPY65hwv1/JP08zQx+pd9ihL/qG11oH1VMs5Aw40hpCQ",
	"ZIuUUGP2eJ6yJSTo7PBkqHCUEkwlImoVFcdU22uGY4mmOL5VB9XKsUO05MOzhmWJyyLLMF/2ZF1p6iNR",
	"dLOtnwCncrGMBtERzDlOIAmwqo3ZUx3aaozOKt7gnXUCnKleoQT3YRAdKoKZqWpwSeaK2V3A5wKEbKOt",
	"syrintyMuP04U0uPBJlTSFBctUUzzjKN5cODNtXinPwCXOgRmwAcnJ/YMpRYdqhJyXyDBJldacibiAos",
	"eyTN1J4xVDNCl8BVQyQWrEj1UX4HXE0lZnNKfit7E47MUyzVtAiVwClOjWRl5IAMLxEH1S8qqNeDriJG",
	"6JRxQITO2D5aSJmL/fF4TuTo9o0YEabYSlZQIpdjJU9wMi0k42KcwB2kY0HmQ8xjJV3EsuAwxjkZamCp",
	"XthRlvyFg2AFj0EEt/ItoUkblz8TmiCi1svUtIJiiTK3Ty+OL6+QG8Cg1WDQW/QKmQoRhM6Am5rlSgNN",
	"ckao1H/EKVGCrSimGZHC0YvC8wgdYkqZlsuKPMESkhE6oegQZ5AeYgF/OCoV9sRQoSyMzAwkTrDE686F",
	"M42jU5BYtRL2YFrVonN3WUkvEuURsV03pnmTv3r7zZKKN0kLeYjlrga3RW5/5zjPQZ0FrKAJwuoU48OY",
	"g1pjdHh5MUAZSyCFRLHg22IKnIIEgQjTa4tzMvJ4iBjd7Y5WgtDmLPAlJ9wIYxAzmojQ0abbmytVyTTu",
	"cEoSIpeao2kCrgZWw8wYz7CM9iNC5cu9imoUp5gDV9iCL5LjVRfCUthoUVxdmGjdFFXHCEtD6yDc0a7Q",
	"a9QKDsea4So85ywvUv1putRfD85PkNAbWOFe11czV4yNZFkh1e0zcC80dBQ8KdSFa4oFvH41BBqzBBJ0",
	"fnxa/f758PIvuzsKnBE6xTJeWE6uqG1Unh8E0gQRirBPD6sOIcOkaksyXUoI7WN9LPEPQRHphCaGyDRM",
	"vKQJ08ZwfM05Pxc4JTMCiZagg/yiIAHee31y9ATr5AEh8DwkAF/r7xrrahr6MAAtEt/CEplW3vztVYAI",
	"UdRP9Jq0vJaA1ZTXy6ZPgJgGJ3TUXCOOzVhfhxBfERTOc87ucDpOgBKcjmeYpAUHJEqJtJylp18QHXhH",
	"ZFZpDUWb43lVw3vUdtmW0QYV4hBTon6J8167S7FXzeYCyDgsy4zkrVaW+TtthH5W0imKvYoc0IFGHSQD",
	"dASUqH8Vht5ikhqgel3XysGD1zSfGrwpBGmg7Kh7gtXyJSAxSYU+QBgFhNWWk26544JzLRBJtaZOeFVE",
	"feGxtPrSpljIK46p0CNdkS61l6qHJMnAjFSCJsu2kBgxTcFlyVAyhCmTC+C11Vby2FD1FRaMhOIXbSh+",
	"KjJMEQecaGqy9RAxe0KJmQ47eMoKaSEuwQsyNDbV2z15BxTMOR2e/chJMqN5WdMwlTo27rHQnE+dWQkq",
	"cjOsf66/fhU81zlgEbypoOdTTmD2Apkalejgxnwmes20p9DnenVCnuupZzOjPm3sAN1DCcEgRHIlAqr1",
	"X7lZ1ms5ajgaaKJkM3TF1U3rLU4FDJC9vfqXc1UeDSJdYePreAM621fjq+u68bl2k65hs02P1rBSUR3x",
	"LzbebByniwbR1fnpL8C1jGEu9K7A8EA9Z8UA21XjGIQg0xSafzieco650FUvlzTWP35Rcq6qwdKUFfKE",
	"nnM25yDU4l+r25hV2uYQu6qnRSpJnsLZPQUuNFx3JIYjUBcxItS1QjXqtxDHlLM0zYBKe556822V1afb",
	"eSR7XXTWKXHZWaNEcmeNOjgXkDNBJOPLIOoVxjsLWuvjF5Zr9TYFkG4V9B+hVTOr4a2d+eCvoPnSdx0N",
	"mc/IvKly7afYfUdkoPk6K8bPpfR/CTEHuYUJZItRf5IyDzXTOMgLtyqnjKqFblu/6ud1Zqqtt7tWqhaG",
	"bKP1oqvfe1DvvtoU2p6JmSVn9PhLrmgpLOhwRhGUFZA5L/VRp/pOilQrkUgGYjShapK2BhHo01+R/f/T",
	"PhqiU0LV7XUfffrrJ5TZG+HO8LvvR2iIfmIFbxXtvVRFR3ipkHbKqFzUa+wOX+6qGsGi3T2v8d8Bbpu9",
	"vx5N6GWR54yra4ZaSCyZAmKoKu6Xl1YlfRvF2XMYzUcD3Q2haKFALvuDO+BL/e2FGvfT8NM+usB0XrXa",
	"Gb75pBG3u4cOTtXav0EHp6b24NM+0qYKV3l3sLtnawuppeDdPblAmcahaTP+tI8uJeQVWGPXxgDTbHFp",
	"LHj1ubypUKLO5Tdekwk9Nl4ICnNoZ/hmsPt6uPfSLmlQlDkshGSZYSwndMZWqUOa0pTWFhmdb4Ji3RGy",
	"G8wuQHDI5nXX64RQQ4z6oqgFz7revyXEGMDbwJnvdRV4vlgKEuPU6++blvublvublntcCSD9bze2zRb6",
	"65vOfdwyzbftxmEdVeM665vOV9vI9V0pWYZPf+NUYq8HEhMlhaH7BYkXWvehW6Jepng1jPZcCfDRD+Uo",
	"rg5yN+nyghru3bvy9luzsBPJw6DbGl/dAW2V0tCtN1kDru2M883rcYfup7Q5q/XyEFpOvhdd1W2uoVNN",
	"mAqOfhba/NvwSAiYpOtkSuxRupJM/dPOqFsc59NKCN8D4lEUEqsN8k18r8WqkcO7EHno6c8qLYLBl9pP",
	"MzJvo40DTYBD0nkMX9gK7uDt7HedVrk+zspJCpZ2Shi22Bc0rLJEf44ZpRBbvUK52O15CyOsnxyFGZEt",
	"RidHvsqqMUKYMEzLU+/oaNB7KeuVozhG7VibgtuaH/695uoYY6pPS2G0xYQSSXBKfjNqzdJnFXhGKE4H",
	"JcySuWYDBDLuWi6cnNF0Ge1LXkCDNBuzGngI7F5K/97cRoTrzMqd2JFUUr9tl/rw1hpKzOcg+x2bPihX",
	"ul1Y2We67Dclr582Gy+NSWazCDVCa2oZyAVL6lvKV4FdU9AKH63giiXjywsQvR2NV0Hs9byqWn3UEgsn",
	"6hzkRC4PFxDfdjGk7rrN3VtnWcS1QLFqgnLgakcYm/iWZ8AweAZUN57mmAair2D93ZPfjvd39rRGi7wB",
	"Miuqc56b11S427+vYy1VfJvQYWgC1Uir6vgwdNcroeuuUsHdRmunTt4KJ10k2tq7eeMGr0dJ1K1DLrcn",
	"GkUIG4s4FXlr8aYCeo1wo2qXuGqfjyRTkmCWu7k3Or/TLSsZtZ/hbKtdZT2XzRI50Vrm2dfgeeuN2Qam",
	"99bsPAA8ZXpJ3+HtudVWbGyLjil17aw1e7i9fatt957MIF7GKWwlzKau9SNcA5pKr6rzxzoDGnPdjv2H",
	"OukiLz92KYSxNp83ZiW7xnVbR/3LhoTWgLpJKo3iGhSB8hBoa6rViO5MhJ3y/FJkiqZWcDPyIDq7LK8B",
	"nbJHFjT7X9U6Mb7gRlnC0fXF+/UXJ9NvN2Gcia220Nll7yn8Ur/4uWkE94UuOSLzTne4RJc1+zKqdiQW",
	"eO+71/t4ZzQaveiLmvqg3Ygq7YcboavUtq476OO86McO6nC4Qysh4vZr2meQMb7cvoem209eRGWnFrq+",
	"qF1t3BM1655BttFlt0MM/o653eiHnEgS43TrYIMQoH4sQ7u0GjxU6gEUKnZAhsp8ZwlPD9zBlhpMCa+w",
	"pVS6pn5BPrk16G4V5tMwIrfcG41iqBsQU74FDEEbdmh4wdKQglW7gzlsxJLcVaodq9PoD0tdYxX0Uq4f",
	"WRvrKrSbV0847PlmdN+GawXUTwq02h60VnO7Itbhuz8OGnbzEBZMkHfSoWozhdpzlShGW7f4N/wHsIwX",
	"51hK4DSoS3Yrqyui3NasTaalfjY2XwdHQYnUR/TABL0yrv9VUqIoZjPyZYBMRM8C0nQo5DIFNE/Z1A2m",
	"4dej4zkmVEjn2JguUcpwAmYIDVOGv7wHOpeLaH/vu9eDyHYR7Uf/++PO8Hs8/O1g+F/7k8nwv0cT/d/H",
	"yeTmf0wmw8nkr5PJDzd/e/4f/eq9+OH5ZDL6aCqGiv8tdJqvD+AzdrtzlpK45+Fz7bUw5PrQea6sViy1",
	"VUlhuV54sYOWeSLbNsP6LkxSY/OJZYHTyv/0a3mtFbV8luufdxtwmLaZLrDLcNvYsHHvDWNNfx/mchU0",
	"Jo05zRluFCaDDr4+gr/Wb9k/cXqx7MqSolUr9tK6lQLC6UwuAWgf/2NLGMbdFqjz37ccED3/cHZ1vG/s",
	"faV3BxGIMok4yILTms//i55KFiUXzdnwV8HokMwp42A0/Qp4d4Pa6ka74RlVtqmdUpuKrfpc2YTKW5Rt",
	"GL5zwenRQVV/1Znmdn/tPNl435vBkmtKZPeOt14TmzDepEPN5W3zGmbqbCUKcxl/Kf29VO5JTR8VvNXK",
	"+aTXfb/Y3oLs7bYF5sk95qB9eIwrG6Fzu0yo5lXz+JZlC4MLLHgM23IANdupljaKFA+rKc+0d2k4KPwC",
	"poxZv9tzdg8ckrPZrKbHPLjHRGonYmtcNR7ms5TE8hwXYkOtU21CHmitMg/aQGn9Dlcr8ucUKK5NM1De",
	"1IPVCkPICFRr4qdazhpb6+dZeJY7i7TZDV4gJXzJmajOGzwHKkcTeozjhQ6PixnnIHJGExMwU10jzLaw",
	"/nMxzvGUpEQuRxO63kfRTKK2q2KWpibPT+lo1imeKSA7PRrUeXww1zmFTJXgJvR9xzr68Goo+cc4yVo8",
	"tTwoq54V6YT8Dn5kTKKTo026Mi6gfY6wltepOrMdEzTYDs/yrOSUl45T9gSv6aHmI7TEQhuKQX35uvlW",
	"6yaxxgif65pakZthiucm5krzZXMw6VxScVokquR+AdR9d26jU0AJu6f2FqfOERu6F7D72XqXxgN8rWBl",
	"JlPWLg/3bds/rEFbspXW2MD0qFYX/3g03T/m8Vib7HbHY7uLDewuFcJKo0t+xY6wjhc9K+TZzP72glO2",
	"UWzWgPSGCJT6owYbN6Jk6qW+7pKI27XhHxtHXAz+yUJGghzF3uY1KzEdaGZCxK0JF98kQWJCOGgnmzJD",
	"olPIqe7rfa6ey4p8fUeFHx86w0Wq7oo7SihvQ5ThLyQrsir5A05Tdu87xxoHO8lQbDN5mWR7ZYOKX7qg",
	"+gRhHRHA1Ma+s7ZvUHO0fU+XCJsbsrowjVAVdlJ+1AHQ++iTMBEcwqSvGKBPmflggjLUh4X5oMNP9FpU",
	"erXnP+x/3B1+fzOZJH998cNkknwU2eImqP46pjFTZ0EfDy+wdQ01agc9vXxY4kZkgs8M8hQTJQ2ZJBG9",
	"4wPNUOe2sfv7R9vJQyBMsA1+q8qK7EU2Wl8tuPEaW6ka+xbS8S2k408Y0tHaUJtFd7SbP26ioo6oYpz2",
	"YA2uapXJISzLlYzC0+1ajqFzuHZ68mIXnrwiZ8j9AuQCuJ8iAy2wQFMAilwH3ppPGUsBU6ObnUL6NYlo",
	"D1xCGNOTvujmebqsUv91xMu1Fs/Oc6MVqkT1fnJV91K3BZo1g65bcc+28rVrf9DhMaKPfyxtGJC/+vdY",
	"1Ba+n6Oha/FjVwxSPZRJ1e0hR3q9DvwpBcSxwYZLsIWBK4D4coFGQVoLX6CD1cyp41U0I7fqPhPO80kb",
	"fAIuM4KHlyCUJMvP9yNMzgGfpgIbuG5B7B9ZN4j0HediXWTMlSbFldEx+vy0zv+jXwWj6DmzqrYXHZ63",
	"j82pXJYXZ1zSydQ95kVEaY5aAEXqQPeIh4gQa+3gbmo9ezG2Lt1DR8XNdkCrky6WY46+rRipZx5dl1vK",
	"p+V2gqnRxmmj2kmSIDzlp00E5SedD+IhNoVmjWYk5Lsbr2qvr0pIwheJnl9fvR2+eYEYb2bX8wbRcVQk",
	"7cSwquduTuvpwLsIBlVravrdIV+qtAzyas97zlmRh2etZvBMIF1j4F2mgWhZCLtE2DYjO3ASo5OjEToy",
	"d3wtqUwizpicRGF5mCWwcugcuHVF0pkpR+g/WaGvCQYYowPOlFA/wxlJCeaIxRKnVcZ4rO/FvwFnLqPC",
	"zutXr/TyYXOSxCSzDUwgWKjNq72dF+qeIguSjAXIufpHkvh2iaZWNYBKT/MROplpc3mJsYFRAdcno2+3",
	"ap6KB1YIU+CFg34LAXwltti9To346AvVRXObKdw2eRmiRtHrKteeEwk+I1HuuQ4FVTglTisYfU7khQIj",
	"fBZ7Cbkxekdk3aXN5kbcRDfnNHI2/nNG5i5Es0pt1BF87orXC5lVV7XcnW1vLC1MXcAdWSWPmFIFdCG8",
	"HNMr4W3F6pbAt0YddGkZVz064c+24ffZO/O5XfnQwB0pilrEs5Ay70k9FP10dXXek37U3g8/pKO+Ooox",
	"UtYzYd60sYZWybx7jTu9mj4+GhQBd8A9xar3EM5XUR9vU58jHmyDM5c0Rivo0nhFhibPy5P4+uK9zWLK",
	"MhAIz6S9yasDXAdCoBOpw5uNBQ7Q5wK0SpzjDPRrJKKIFwiLfTSJxooGx5KNnVrqB13733XtLv7ZSeHl",
	"8j09UTuKDI288sWTbR6YCb0kUXuLIhB20uTl7g2DSL+Z0pCqXdn6pxLODk+q5xACKTdQjuNbXCWGsg8s",
	"oWlBkxTEi+7Ykx6Dl6lFbOzJivF7ncSdi3depGnlGluZXU5mH5g8NzealgHGuWLURYNnfptnI/R3dVdT",
	"Nz1VdpDe46V4ZkQcMyciUF6kqRJAdJ4r8yBSrdUHVVJrpJ8CwqnJsqKT6XbHCJsxo0FzMrrXnoYMhZ+y",
	"H/VHoy/1yfbnUNrnoZOSDnq+rXKpWdsGgVfttgEPZT+KzLJVY79Y8zpIQDypkdHaSXlUt8EDJusBMynI",
	"OcyJkHw5QlcLYuwFUzBeP7VNpRqa3Lmlfdbf9AN1uKSMztW/VlBjPBM+gzAdCd/i2oezr3ogZfVDUI/I",
	"VJvuEdoHbUW4gs97rBiwTVBOJdyvvsxbgG768bKu1JH7m8/TXLYks9nM2/yl14zLm0/AJ/aPPbA7ETeI",
	"Vqbn7JlVa3MwB5HQo/W9FVVQItMwEGPDCiq3lGdrenozgCez6p5rmsRqGv0QUsEc7EA/PNfdiy5e21V4",
	"5avuBx6GbtbpRG3rapFCpHOq4yz/BKlUPatq2we1LFPSS5kSybwJmqYoBy6IfoChisnVEssC38HAkp29",
	"PQjdwkCrE6hxW9ewnYBGmFImq3ieLZXvVWWTRr0W1hHMpukeaShzaqywgZnAGm26v8fCvQfR3/CVQArb",
	"jGVfX9XNNxlvviIr/QES8LnQbMnm/Ks5LuDy2EdexvrStmKSKRmrEjpvPoPhnpS9AJwMGU2XPZPYf7Xt",
	"5RTrlCjWH+MWlqJ6etRaYhoJvBifY0p+MzEJMZYwZ1z9+VzELDdfBaQQyxeOmINU1I93WseZ4EMC9zSk",
	"2DzwHUewROxev8GhPXPM94E6DSbaD2GsxppENrlxV0pG3arbQYgiluPPBTgk6mGJzp5TuloZNcwz4Xny",
	"VMa3ykGonxL1HMt44TlJlfJHmAZmOvd+g3mwjp1kPZuNNs7mXfLvUDhJdOhMnppjhUPG7vRWqmcyqBAY",
	"1lQeoP95efYBnTONkPKF5lZrTYhhUI3zkJIQkkTJ7haoUetcYPkqFWBTGKs9L7zymWnEbdXNX5k+CLR9",
	"1OelBY/HhCbwZfSr6EdV7gA8SIHLC+u+nXcHYLSntKgnLWtY27W6QvUdNn0XXWzXuYGqE1Y6Xq/m7Ult",
	"+A64ungVwioSytyoU5gxbgcmdD5Cb/VW31/t1flMPKu7az7LntXdNZ8tnnW6a04myd+6PTRz4DFQ2Zl5",
	"pSpXWDMzMhZxTuZzJRWEMGlOJCNb30GfqNDael/aRmF3c9ejt0y1edQPlZt1xFUbrO2jaktbNONYUDDD",
	"ho4P6afC6YSl6rizijdiZx0Dijdpl2VATZWoqWaEYvshw3lurbmH59edJu/wowXGn73TQ6TD193J7l3t",
	"uiX7h5K5Lc3zazWRW53JvZ6S6JjNOgl9FVxrfGU6MPFws+IC0V7AlQE7Yfd6XDOPNeR3x2hXZbzQlRBX",
	"tUbojKZL8wiV/poDR25vaq8Xw8A2zoJRcfxQHgx1ohA6P1HndND1smTQ7nF6Fwugmyq4n4Dnlv7xXYx3",
	"xV1x4C9FYMYhhrbmOSRixANZcGrlFAV4jFPn3pQw+sxZzZDROXrS8jf39D/WPT0OepBcFvO5eS5RWy/t",
	"4sTO6ULjz3htDdAOItZbw+hjejwk+s0n/lF94jverOsjhvpxggqP7s7Tlfq/4524DMcLQqFzqPvFsjGA",
	"Wmiripzo5JgFV9dPm7QRnViADAkQgSDLpVYQcDDJNOq+hHeYpPqBTHSALsxjdXGKuX0Q1PoDCOcUnQCa",
	"ForzgEnLoWRoThJARK6JWVwVWF8hD53pF9/20SS6LPQTWZNI3cu8mf7hZCNyiIeYJsPOPJg9QhPKZ/M0",
	"m+j5UJ5NfnGgs3MpFEG3lnNB5othqiZlMm3olF5Vsp2a0dKk+9JQpEy7mGmVfvl55hKduk50hQRqf2ZY",
	"8SGKqb2zzziIRf/X3dpzO3DDt4suPDjbpScV5O3CMmlrx4DlM3at4qP6fNsVTmsYCEFd4aRazWOqttea",
	"1QRdqe7dqpfVuXK6pTQVE/1F/xryglpNZErorS4yP7wSnBIs9BoKU8P88GqokUlsUh66EQg1MZpRqdPU",
	"n02YsjFVT3Gy2fp72Dgup9JZdlHC167y3s22q2hV4wOLkHbJqUNRV9Gqbi8dFttFRxVe24UnFabbhe88",
	"3AdoyluNdumPOPFp8T3DyRpKVBuvBx0KWUwVpTGbR4QyOZyxQvO+KU6GAqTdR2DTiWTA5x7tbUY2JeCX",
	"Ztzm5/cOjmbBBybfWrCaRT/i5LKEslnokqA0v5+6WbQK7KwqZHs5jFpaMFxxjZ4ZkZqHQlMLHzwjuqUY",
	"5/yjg45rWr+zHOjl5U/uRe0EQ2YOLi9n386rN4HDHiq66zmpJm98MBS1SRd1ktZuedOyfYi8782pOdBT",
	"H6pJDEujS3VylujgBaXuACwR8PpV/eKIh7/tDL8f3vwtqK1TA4WhKXMuOoevSSTEIhlZ09kketHQyHqF",
	"a8USPWydSupr5CN7UCNJD4shOeWKZPBfzHk8OPeu98wotdpZ89FvjEJlzuDCXto1BZ4cfDhwL0MeXBwf",
	"jN+fHR5cnZx9GKB7LbSqj/UgbSXYEaoDHjhiMWBq7ouuZe1J+xxzSeIixRwJIkG72xP7DDTmgAfmWUSD",
	"Y3SgXdTx+APc//d/Mn47QMeF2rnjc8yJU58UFGdTMi9YIdDLYbzAHMfasdPNteGWj55PonenV5NILfD1",
	"1aFd1xahXLdSnzS9q6rbuX1i01wrcSGZEujjMk+LVhzRJJThRZLMlbqgLA05K0IhQ2vfmWk8E2qEfi7f",
	"cRyDn35hpXLN1XsYRNIjrlVtSiJsieMhX/sH7x0J7bNl/DUhwySN9iMJOPuPWUrmCxnLdERY5KyLep++",
	"1SXoUF0oWIquAGfRICq4auquILXWLRvpx3oXN89DzV7YS7wNWdOJFEDdxoyVR2fvgcwG+sxSAKmvUJDM",
	"nVuKsbzKBRCO7hm/VaQgTOaplMRABVROONFBjuMFoL3RTmsy9/f3I6yLR4zPx7atGL8/OTz+cHk83Bvt",
	"jBYyS82CSc2cGkg6OD+JBtGdUzpFd7s4zRd412Zgojgn0X70crQz2rWmNU1w6kY2vtsde8FiNuzR6Rb0",
	"acpCuR0OjXMVRp3vNNdUqeW18yQpG3e2jAyRgZA/MvOMnxe25bmxjX+1N31Dp2t3T+d4D3W6thkrTc4x",
	"YTbn3s7uUwESQnSilvLVzs6jwVCG/rcG/BEnqIRHDbr7BINeU1zIhfZMsFN9+QSjvmV8SpIEqBny+ycY",
	"sp5ZT4+79xTjXjGGTjFduqXVkaXfPQmWLw2PvaalAsxYtPFcXzs6uU90o6qtZ1Lj3xWTfdCxWxAMDcCJ",
	"OcfLkLnOHdjmVe9ArmJUVfSItqOtdo9ZzyuRZGhuVNRE9WAD2+wpUr6W6XOqgbdAzVteQcnnAk6MdUmz",
	"NWNDqzG2nX8MYzv7+U/GXl49wZDlHfwbY+nLWKw0Z7nI2KVb6GQn70DaqDablyFxz5J3iTvvQLpMD/Zp",
	"8w35hn343PCG+uCiac5+HNbx0E7jUuYY16krUOO11XJYHSZXjRvMc7Fq3D+SP1nsdzKjPbNHm1sKeTEP",
	"/yh+9UTMA1Xc40nEoX8KQcjjGWYvr2QQlZ0txzIORzC46AQvZ8jROi6hm9XSxGzHJXxRQkP4WBzhZpNr",
	"2VAP/bfNVq3mKdvrUvZ0vOHb5etfQjpCfzrxCHXJRyWvG0R5ERB0rm2q5E0Z2YVx7H5kVlalOX5yXrYd",
	"E/nGuv4kgtI/qdhSpVjrr82lKJSzd7Uat50I+I/ZW+1xnlht2wHAN3Xtv7C69s+oqO0UGFocZR3DWaeZ",
	"fQdyU57zDmSI4WwkXXSP96jq1z9Wl9GLG33TsX67RfwjmIKOa9Ou7Xo7GoP32OT+MO3az0PZXS4Qo035",
	"XzsG201oRZ22frLeQ/ce9ztrA/9w8/D/AwAA//9xQv/11LQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
