global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus scrapes itself (for its own internal metrics)

  - job_name: 'flightctl-telemetry-gateway'
    static_configs:
      - targets: ['flightctl-telemetry-gateway:9464'] # Telemetry gateway for Flight Control metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+)(?::\d+)?'
        target_label: instance
        replacement: '$1'

